const faker = {
    "insertId": "64ee4958000c7ee91c1ed56b",
    "jsonPayload": {
      "actor": {
        "type": "application",
        "name": "Sentry",
        "id": "sentry"
      },
      "action": "triggered",
      "data": {
        "triggered_rule": ".NET Test Issues Teams Integration",
        "event": {
          "debug_meta": {
            "images": [
              {
                "debug_status": "missing",
                "features": {
                  "has_symbols": false,
                  "has_unwind_info": false,
                  "has_debug_info": false,
                  "has_sources": false
                },
                "debug_file": "C:\\adoBuild1\\_work\\3\\s\\BuilderTREND-LIB\\obj\\x64\\Test\\netstandard2.0\\BuilderTrend.pdb",
                "candidates": [
                  {
                    "download": {
                      "status": "notfound"
                    },
                    "source_name": "Android",
                    "source": "sentry:android"
                  },
                  {
                    "source_name": "Microsoft",
                    "source": "sentry:microsoft",
                    "download": {
                      "status": "notfound"
                    }
                  },
                  {
                    "source_name": "Sentry",
                    "download": {
                      "status": "notfound"
                    },
                    "source": "sentry:project"
                  }
                ],
                "debug_checksum": "SHA256:acf82b5ead634fa3dbb9e105c611f69d843e233f86779755ca2c51d0351cb2f1",
                "code_id": "d0c6681d5a0000",
                "debug_id": "5e2bf8ac-63ad-434f-9bb9-e105c611f69d-bf233e84",
                "code_file": "D:\\test-blue.buildertrend.net\\bin\\BuilderTrend.dll",
                "image_addr": "0x0",
                "type": "pe_dotnet"
              }
            ]
          },
          "culprit": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs in string BTSqlString.get_Value()",
          "key_id": "1682840",
          "platform": "csharp",
          "dist": null,
          "_metrics": {
            "bytes.ingested.event": 24752,
            "bytes.stored.event": 43528
          },
          "web_url": "https://sentry.io/organizations/buildertrend/issues/4435517859/events/1ee15d3b4ce14169b285602bd9905841/",
          "datetime": "2023-08-29T19:38:43.333021Z",
          "sdk": {
            "integrations": null,
            "version": "3.25.0",
            "name": "sentry.dotnet",
            "packages": [
              {
                "name": "nuget:Sentry.AspNet",
                "version": "3.25.0"
              },
              {
                "version": "3.25.0",
                "name": "nuget:sentry.dotnet"
              }
            ]
          },
          "nodestore_insert": 1693337929.118081,
          "modules": {
            "Microsoft.AspNetCore.Http": "2.2.2.0",
            "System.Threading": "4.0.0.0",
            "System.Web.DynamicData": "4.0.0.0",
            "Microsoft.Extensions.WebEncoders": "2.2.0.0",
            "Microsoft.Owin.Security.OAuth": "4.2.0.0",
            "System.Text.Encoding": "4.0.0.0",
            "System.Resources.ResourceManager": "4.0.0.0",
            "FirebaseAdmin": "1.9.1.0",
            "Salesforce.Force": "1.0.0.0",
            "Serilog.Settings.Configuration": "3.1.0.0",
            "Clients.Hangfire.RecurringJobs": "1.0.0.0",
            "Google.Cloud.PubSub.V1": "2.7.0.0",
            "System.Net.Http.Primitives": "4.2.29.0",
            "Buildertrend_WebLib": "1.0.8641.32948",
            "OSExtensions": "1.0.0.0",
            "Microsoft.Owin.Security.Jwt": "4.2.0.0",
            "NPOI.OpenXml4Net": "2.5.1.0",
            "Newtonsoft.Json": "13.0.0.0",
            "MoreLinq": "3.3.2.0",
            "IdentityModel": "5.1.0.0",
            "Snappier": "1.0.0.0",
            "MongoDB.Driver.Core": "2.19.1.0",
            "System.IdentityModel": "4.0.0.0",
            "NodaTime": "3.1.9.0",
            "Hangfire.Core": "1.7.33.0",
            "App_Web_externalnonembeddablemaster.master.af2f93c0": "0.0.0.0",
            "System.Data.SqlClient": "4.6.1.5",
            "Microsoft.VisualBasic.Activities.Compiler": "10.0.0.0",
            "Microsoft.Extensions.Configuration.Xml": "2.2.0.0",
            "MongoDB.Libmongocrypt": "1.7.0.0",
            "Google.Apis.Auth": "1.55.0.0",
            "System.Configuration.ConfigurationManager": "4.0.2.0",
            "UnitsNet": "4.0.0.0",
            "K4os.Compression.LZ4": "1.2.16.0",
            "Grpc.Auth": "2.0.0.0",
            "Microsoft.AspNet.SessionState.SessionStateModule": "1.1.0.0",
            "BT_Encryptor": "1.0.0.0",
            "Google.Apis.Core": "1.55.0.0",
            "Microsoft.VisualBasic": "10.0.0.0",
            "Microsoft.Extensions.Options": "3.1.7.0",
            "gma.Drawing.ImageInfo": "1.0.0.0",
            "WebGrease": "1.5.2.14234",
            "ChargeBee": "3.8.0.0",
            "Google.Apis.Auth.PlatformServices": "1.55.0.0",
            "BusinessLogic.Managers": "1.0.0.0",
            "Xero.NetStandard.OAuth2": "0.0.0.0",
            "System.Web.Optimization": "1.1.0.0",
            "Microsoft.AspNetCore.Http.Connections.Common": "3.0.0.0",
            "Microsoft.AspNetCore.Hosting.Server.Abstractions": "2.2.0.0",
            "RestSharp.Serializers.NewtonsoftJson": "106.11.7.0",
            "Microsoft.Web.Infrastructure": "1.0.0.0",
            "Microsoft.Build.Utilities.v4.0": "4.0.0.0",
            "Atalasoft.dotImage.WebControls": "11.4.0.349",
            "Microsoft.Owin.Host.SystemWeb": "4.2.0.0",
            "System.Drawing": "4.0.0.0",
            "App_Browsers": "0.0.0.0",
            "CsvHelper": "15.0.0.0",
            "Google.Api.Gax.Rest": "3.6.0.0",
            "App_Web_default.aspx.41cb4f82": "0.0.0.0",
            "Global.DependencyResolver": "1.0.0.0",
            "App_Web_loginnotrequiredmaster.master.1880769f": "0.0.0.0",
            "Microsoft.AspNetCore.Http.Features": "3.1.0.0",
            "Grpc.Net.Common": "2.0.0.0",
            "Hangfire.Console": "1.4.2.0",
            "Microsoft.Extensions.Http": "2.2.0.0",
            "Microsoft.CodeDom.Providers.DotNetCompilerPlatform": "2.0.1.0",
            "Intuit.Ipp.OAuth2PlatformClient.Diagnostics": "14.6.3.4",
            "Google.Cloud.Kms.V1": "2.7.0.0",
            "System.Diagnostics.PerformanceCounter": "5.0.0.0",
            "Microsoft.Extensions.Logging.Debug": "3.1.0.0",
            "System.Workflow.Activities": "4.0.0.0",
            "System.Web.Cors": "5.2.7.0",
            "Microsoft.Extensions.FileSystemGlobbing": "3.1.0.0",
            "Swashbuckle.Core": "1.0.0.0",
            "System.Activities": "4.0.0.0",
            "System.Web.RegularExpressions": "4.0.0.0",
            "System.Threading.Channels": "5.0.0.0",
            "Intuit.Ipp.Exception": "14.6.3.4",
            "Microsoft.AspNetCore.StaticFiles": "2.2.0.0",
            "Microsoft.IdentityModel.Logging": "6.10.2.0",
            "Microsoft.Extensions.Configuration.Binder": "3.1.0.0",
            "System.Runtime.InteropServices.RuntimeInformation": "4.0.0.0",
            "System.ServiceModel": "4.0.0.0",
            "System.Core": "4.0.0.0",
            "System.Xaml": "4.0.0.0",
            "Elastic.Apm": "1.16.1.0",
            "System.Net.Http.Formatting": "5.2.7.0",
            "BuilderTrend_Web": "1.0.8641.33078",
            "MongoDB.Driver": "2.19.1.0",
            "System.Runtime": "4.0.0.0",
            "Microsoft.Owin.Security.OpenIdConnect": "4.2.0.0",
            "Serilog.Sinks.File": "2.0.0.0",
            "Intuit.Ipp.Core": "14.6.3.4",
            "System.Diagnostics.EventLog": "7.0.0.0",
            "Intuit.Ipp.Diagnostics": "14.6.3.4",
            "Handlers.IntegrationHandlers": "1.0.8641.32917",
            "BuilderTrend": "0.0.0.0",
            "System.ServiceModel.Web": "4.0.0.0",
            "NPOI.OOXML": "2.5.1.0",
            "Microsoft.AspNetCore.Http.Abstractions": "2.2.0.0",
            "App_Web_default.aspx.cdcab7d2": "0.0.0.0",
            "System.Threading.Tasks.Extensions": "4.2.0.1",
            "HtmlAgilityPack": "1.11.24.0",
            "Serilog.Sinks.Console": "3.1.1.0",
            "System.ComponentModel.DataAnnotations": "4.0.0.0",
            "Trirand.Web": "4.5.4.0",
            "Ude.NetStandard": "1.0.2.0",
            "LumenWorks.Framework.IO": "3.8.0.0",
            "Sentry": "3.25.0.0",
            "Serilog.Enrichers.Thread": "2.0.0.0",
            "Microsoft.Extensions.Configuration.Abstractions": "3.1.0.0",
            "PuppeteerSharp": "10.1.2.0",
            "Microsoft.Extensions.FileProviders.Abstractions": "3.1.0.0",
            "Atalasoft.dotImage.AdvancedDocClean": "11.4.0.349",
            "Google.Cloud.Logging.Type": "3.3.0.0",
            "Intuit.Ipp.QueryFilter": "14.6.3.4",
            "System.Security": "4.0.0.0",
            "Microsoft.Azure.WebJobs.Host": "3.0.18.0",
            "Atalasoft.dotImage.Ocr": "11.4.0.349",
            "DAL.Core": "1.0.0.0",
            "System.ServiceModel.Activities": "4.0.0.0",
            "Ical.Net": "1.0.0.0",
            "Grpc.Core": "2.0.0.0",
            "Clients.Atalasoft": "1.0.0.0",
            "System.Data.DataSetExtensions": "4.0.0.0",
            "Google.Cloud.Logging.Log4Net": "3.3.0.0",
            "System.Runtime.Serialization": "4.0.0.0",
            "RestSharp": "106.12.0.0",
            "Intuit.Ipp.Retry": "14.6.3.4",
            "System.IdentityModel.Tokens.Jwt": "6.10.2.0",
            "Microsoft.DotNet.PlatformAbstractions": "2.0.4.0",
            "mscorlib": "4.0.0.0",
            "BusinessLogic.Engines": "1.0.0.0",
            "TimeZoneConverter": "3.3.0.0",
            "System.Net.Http.WebRequest": "4.0.0.0",
            "Microsoft.VisualStudio.TestPlatform.TestFramework": "14.0.0.0",
            "System.Security.Cryptography.Xml": "4.0.1.0",
            "Handlers.DataAccessHandlers": "1.0.0.0",
            "ICSharpCode.SharpZipLib": "1.4.2.13",
            "Google.Cloud.DevTools.Common": "2.1.0.0",
            "Xero.NetStandard.OAuth2Client": "1.6.0.0",
            "Intuit.Ipp.EntitlementService": "14.6.3.4",
            "RebateService.Shared.Contracts": "1.0.42.0",
            "System.IO": "4.0.0.0",
            "SMDiagnostics": "4.0.0.0",
            "Hangfire.Pro.Redis": "2.8.20.0",
            "StackExchange.Redis": "2.0.0.0",
            "JsonSubTypes": "1.5.2.0",
            "Braintree": "5.15.0.0",
            "System.Interactive.Async": "5.1.0.0",
            "DotNetOpenAuth": "3.4.7.11121",
            "Intuit.Ipp.Utility": "14.6.3.4",
            "Auth0.ManagementApi": "7.20.0.0",
            "MongoDB.Bson": "2.19.1.0",
            "Microsoft.Extensions.Logging": "3.1.0.0",
            "AdvancedIntellect.Ssl": "2.0.0.6",
            "Google.Cloud.Iam.V1": "2.3.0.0",
            "System.WorkflowServices": "4.0.0.0",
            "Microsoft.Net.Http.Headers": "2.2.8.0",
            "Antlr3.Runtime": "3.4.1.9004",
            "IP2Location": "4.0.0.0",
            "Excel": "2.1.2.3",
            "Clients.WebApi": "1.0.0.0",
            "Owin": "1.0.0.0",
            "System.IO.Pipelines": "7.0.0.0",
            "Nager.Country": "3.1.1.0",
            "System.Collections.Immutable": "7.0.0.0",
            "System.Design": "4.0.0.0",
            "Microsoft.IO.RecyclableMemoryStream": "1.2.2.0",
            "Microsoft.Extensions.Logging.Console": "3.1.0.0",
            "Google.Apis.Storage.v1": "1.55.0.2526",
            "Atalasoft.dotImage.Pdf": "11.4.0.349",
            "Dropbox.Api": "6.14.0.0",
            "Intuit.Ipp.OAuth2PlatformClient": "14.6.3.4",
            "System.Collections": "4.0.0.0",
            "System.Web.Extensions": "4.0.0.0",
            "System": "4.0.0.0",
            "System.Runtime.CompilerServices.Unsafe": "6.0.0.0",
            "App_Web_adminmain.aspx.41cb4f82": "0.0.0.0",
            "WebClientShared": "1.0.0.0",
            "Microsoft.AspNetCore.WebUtilities": "2.2.0.0",
            "Microsoft.Extensions.Logging.Abstractions": "3.1.0.0",
            "Microsoft.IdentityModel.Tokens": "6.10.2.0",
            "App_Web_default.aspx.ae7ca9bd": "0.0.0.0",
            "BTSerializeJSAttribute": "1.2.0.0",
            "Atalasoft.PdfDoc": "11.4.0.349",
            "HtmlSanitizer": "4.0.0.0",
            "BouncyCastle.Crypto": "1.8.6.0",
            "System.Text.Encoding.Extensions": "4.0.0.0",
            "SimpleObfuscator": "1.0.0.0",
            "Microsoft.Extensions.Configuration.CommandLine": "3.1.0.0",
            "Handlebars": "1.9.5.0",
            "Microsoft.Extensions.DependencyInjection": "3.1.22.0",
            "Google.Cloud.Logging.V2": "3.4.0.0",
            "aspNetIMAP": "1.8.0.0",
            "System.Text.Encoding.CodePages": "7.0.0.0",
            "K4os.Compression.LZ4.Streams": "1.2.16.0",
            "Google.Cloud.Storage.V1": "3.6.0.0",
            "Microsoft.Extensions.FileProviders.Physical": "3.1.0.0",
            "Microsoft.AspNetCore.SignalR.Client": "3.0.0.0",
            "Microsoft.AspNetCore.Connections.Abstractions": "3.0.0.0",
            "Microsoft.Extensions.ObjectPool": "2.2.0.0",
            "System.Threading.Tasks.Dataflow": "4.6.3.0",
            "Datadog.Trace": "2.14.0.0",
            "Atalasoft.dotImage.PdfReader": "11.4.0.349",
            "Magick.NET.Core": "13.1.0.0",
            "Buildertrend.Utilities.Core": "1.0.5.0",
            "System.Text.Encodings.Web": "6.0.0.0",
            "App_Web_btdropdownmenuitem.ascx.72c91787": "0.0.0.0",
            "Atalasoft.dotImage.PdfDoc.Bridge": "11.4.0.349",
            "System.Data": "4.0.0.0",
            "System.ComponentModel.Annotations": "4.2.1.0",
            "Atalasoft.dotImage.Lib": "11.4.0.349",
            "Clients.Hangfire.OneTimeJobs": "1.0.0.0",
            "aspNetMime": "2.8.0.0",
            "Microsoft.Owin": "4.2.0.0",
            "KellermanSoftware.Compare-NET-Objects": "4.57.0.0",
            "System.Threading.Tasks": "4.0.0.0",
            "System.Security.AccessControl": "6.0.0.0",
            "AWSSDK.SecurityToken": "3.3.0.0",
            "AngleSharp": "0.9.9.0",
            "Microsoft.Extensions.Options.ConfigurationExtensions": "3.1.0.0",
            "MimeTypesMap": "1.0.8.0",
            "System.ServiceModel.Activation": "4.0.0.0",
            "Elastic.Apm.AspNetFullFramework": "1.16.1.0",
            "antlr.runtime": "2.7.6.2",
            "System.Runtime.Extensions": "4.0.0.0",
            "Global.Utilities": "1.0.0.0",
            "K4os.Hash.xxHash": "1.0.6.0",
            "Microsoft.IdentityModel.JsonWebTokens": "6.10.2.0",
            "CaptchaImage": "1.0.2770.19138",
            "System.Numerics": "4.0.0.0",
            "DAL": "1.0.0.0",
            "System.Linq.Async": "5.1.0.0",
            "Salesforce.Common": "1.0.0.0",
            "Serilog": "2.0.0.0",
            "Nest": "7.0.0.0",
            "System.Web.Http": "5.2.7.0",
            "System.Net.Http.Json": "5.0.0.0",
            "Microsoft.Owin.Security": "4.2.0.0",
            "App_Web_menu.ascx.56baee3b": "0.0.0.0",
            "Microsoft.Build.Framework": "4.0.0.0",
            "System.Windows.Forms": "4.0.0.0",
            "Microsoft.Extensions.Configuration.FileExtensions": "3.1.0.0",
            "Hangfire.Heartbeat": "1.0.0.0",
            "AutoMapper": "10.0.0.0",
            "Google.Api.Gax": "3.6.0.0",
            "Google.Apis.PlatformServices": "1.55.0.0",
            "Microsoft.AspNetCore.Hosting.Abstractions": "2.2.0.0",
            "Global.DependencyInjection": "1.0.0.0",
            "Microsoft.AspNetCore.Http.Connections.Client": "3.0.0.0",
            "System.Reflection.Metadata": "5.0.0.0",
            "RedLockNet.SERedis": "2.2.0.0",
            "Microsoft.AspNet.Identity.Core": "2.0.0.0",
            "Atalasoft.dotImage.Raw": "11.4.0.349",
            "VimeoDotNet": "2.0.0.23",
            "Buildertrend.Utilities.Ocr": "1.0.0.0",
            "Twilio": "5.65.2.0",
            "System.Data.Linq": "4.0.0.0",
            "System.Web.Http.Cors": "5.2.7.0",
            "System.ServiceModel.Internals": "4.0.0.0",
            "StrongGrid": "0.50.2.0",
            "System.Net.Http.Extensions": "2.2.29.0",
            "Intuit.Ipp.GlobalTaxService": "14.6.3.4",
            "Microsoft.Extensions.Logging.Log4Net.AspNetCore": "2.2.12.0",
            "Global.SignalrModels": "1.0.0.0",
            "IppDotNetSdkForQuickBooksApiV3": "14.6.3.4",
            "System.Memory": "4.0.1.2",
            "Microsoft.Extensions.Hosting": "3.1.0.0",
            "Global.Core": "1.0.0.0",
            "System.Runtime.Caching": "4.0.0.0",
            "Microsoft.AspNet.Identity.Owin": "2.0.0.0",
            "NPOI.OpenXmlFormats": "2.5.1.0",
            "Imazen.Common": "0.7.8.0",
            "HttpMultipartParser": "2.2.4.0",
            "System.Xml.Linq": "4.0.0.0",
            "App_Web_btadminnavigationenabledmaster.master.7ab75745": "0.0.0.0",
            "System.Buffers": "4.0.3.0",
            "Grpc.Core.Api": "2.0.0.0",
            "System.Workflow.Runtime": "4.0.0.0",
            "Google.Api.Gax.Grpc": "3.5.0.0",
            "System.Linq": "4.0.0.0",
            "System.Transactions": "4.0.0.0",
            "QbSync.QbXml": "0.0.3.0",
            "System.Web.Mobile": "4.0.0.0",
            "System.Runtime.DurableInstancing": "4.0.0.0",
            "Microsoft.Azure.WebJobs": "3.0.18.0",
            "Microsoft.Extensions.Logging.EventLog": "3.1.0.0",
            "System.ValueTuple": "4.0.3.0",
            "System.CodeDom": "7.0.0.0",
            "Handlers.Accounting": "1.0.0.0",
            "System.Workflow.ComponentModel": "4.0.0.0",
            "Hangfire.AspNet": "0.2.0.0",
            "Intuit.Ipp.Data": "14.6.3.4",
            "LightInject": "6.5.2.0",
            "Grpc.Net.Client": "2.0.0.0",
            "Microsoft.Owin.Security.Cookies": "4.2.0.0",
            "Microsoft.Diagnostics.FastSerialization": "1.0.0.0",
            "Sentry.DiagnosticSource": "3.25.0.0",
            "Microsoft.Extensions.Hosting.Abstractions": "3.1.0.0",
            "SerilogTraceListener": "0.0.0.0",
            "Microsoft.Extensions.Configuration.Json": "3.1.0.0",
            "Microsoft.Extensions.Configuration": "3.1.0.0",
            "Google.Api.CommonProtos": "2.5.0.0",
            "GenericParsing": "1.1.3.17129",
            "Microsoft.IdentityModel.Protocols.OpenIdConnect": "5.3.0.0",
            "Microsoft.Extensions.DependencyInjection.Abstractions": "3.1.22.0",
            "Atalasoft.dotImage": "11.4.0.349",
            "JWT": "4.0.0.0",
            "System.Text.Json": "5.0.0.2",
            "App_Web_btdropdownmenu.ascx.72c91787": "0.0.0.0",
            "Auth0.Core": "7.20.0.0",
            "Google.Api.Gax.Grpc.GrpcCore": "3.5.0.0",
            "Microsoft.CSharp": "4.0.0.0",
            "Microsoft.Win32.Registry": "5.0.0.0",
            "Serilog.Sinks.Debug": "2.0.0.0",
            "Elasticsearch.Net": "7.0.0.0",
            "XmpCore": "6.1.10.1",
            "Serilog.Sinks.Trace": "2.0.0.0",
            "Microsoft.Extensions.DependencyModel": "2.0.4.0",
            "System.Web.Http.WebHost": "5.2.7.0",
            "Intuit.Ipp.ReportService": "14.6.3.4",
            "netstandard": "2.0.0.0",
            "DnsClient": "1.6.1.0",
            "App_global.asax": "0.0.0.0",
            "Intuit.Ipp.Security": "14.6.3.4",
            "Sentry.AspNet": "3.25.0.0",
            "nClam": "4.0.1.0",
            "Serilog.Enrichers.Environment": "2.0.0.0",
            "MetadataExtractor": "2.7.2.0",
            "Polly": "7.0.0.0",
            "System.Xml": "4.0.0.0",
            "System.Diagnostics.DiagnosticSource": "5.0.0.0",
            "DotNetZip": "1.16.0.0",
            "Atalasoft.Shared": "11.4.0.349",
            "Microsoft.Bcl.AsyncInterfaces": "6.0.0.0",
            "Microsoft.AspNetCore.Cryptography.Internal": "7.0.0.0",
            "Imageflow.Net": "0.0.0.0",
            "Serilog.Extensions.Logging": "2.0.0.0",
            "System.Web": "4.0.0.0",
            "System.Web.Services": "4.0.0.0",
            "Google.Protobuf": "3.19.3.0",
            "Microsoft.Diagnostics.Tracing.TraceEvent": "2.0.2.0",
            "App_Web_rootmaster.master.7371103c": "0.0.0.0",
            "Microsoft.AspNetCore.Cryptography.KeyDerivation": "7.0.0.0",
            "log4net": "2.0.15.0",
            "Intuit.Ipp.WebHooksService": "14.6.3.4",
            "Persits.Email": "5.4.0.4478",
            "System.Security.Principal.Windows": "5.0.0.0",
            "Microsoft.AspNetCore.Http.Extensions": "2.2.0.0",
            "Microsoft.Extensions.Logging.EventSource": "3.1.0.0",
            "System.Configuration": "4.0.0.0",
            "Google.Apis": "1.55.0.0",
            "Microsoft.AspNetCore.SignalR.Client.Core": "3.0.0.0",
            "System.Drawing.Common": "7.0.0.0",
            "System.Security.Permissions": "7.0.0.0",
            "Microsoft.Extensions.Configuration.UserSecrets": "3.1.0.0",
            "Microsoft.Web.RedisSessionStateProvider": "4.0.1.0",
            "NPOI": "2.5.1.0",
            "Clients.WebApiLib": "1.0.0.0",
            "Microsoft.Extensions.Logging.Configuration": "3.1.0.0",
            "Microsoft.Extensions.Primitives": "3.1.7.0",
            "System.Web.ApplicationServices": "4.0.0.0",
            "AWSSDK.Core": "3.3.0.0",
            "Buildertrend.Utilities.Ocr.Veryfi": "1.0.0.0",
            "Microsoft.Azure.Functions.Extensions": "1.1.0.0",
            "Microsoft.AspNetCore.SignalR.Protocols.Json": "3.0.0.0",
            "System.Runtime.InteropServices": "4.0.0.0",
            "SharpCompress": "0.30.1.0",
            "System.Data.SqlXml": "4.0.0.0",
            "Clients.Hangfire.Common": "1.0.0.0",
            "jose-jwt": "4.1.0.0",
            "Pipelines.Sockets.Unofficial": "1.0.0.0",
            "LightInject.WebApi": "2.0.0.0",
            "System.Xaml.Hosting": "4.0.0.0",
            "RedLockNet.Abstractions": "2.2.0.0",
            "System.Numerics.Vectors": "4.1.4.0",
            "Microsoft.JScript": "10.0.0.0",
            "Microsoft.AspNetCore.SignalR.Common": "3.0.0.0",
            "App_Web_btadminmaster.master.91644b2f": "0.0.0.0",
            "System.Net.Primitives": "4.0.0.0",
            "System.Net.Requests": "4.0.0.0",
            "Microsoft.AspNet.SignalR.Client": "2.4.3.0",
            "Handlers.Merchants": "1.0.0.0",
            "ZstdSharp": "0.6.2.0",
            "System.Net.Http": "4.0.0.0",
            "Microsoft.IdentityModel.Protocols": "5.3.0.0",
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "3.1.0.0",
            "Pathoschild.Http.Client": "3.2.0.0",
            "Intuit.Ipp.DataService": "14.6.3.4",
            "System.EnterpriseServices": "4.0.0.0",
            "Hangfire.Dashboard.Management.v2": "0.0.0.0",
            "Avalara.AvaTax.RestClient.net45": "20.9.0.0",
            "Magick.NET-Q16-AnyCPU": "13.1.0.0",
            "Datadog.Trace.ClrProfiler.Managed.Loader": "2.14.0.0"
          },
          "ingest_path": [
            {
              "public_key": "XE7QiyuNlja9PZ7I9qJlwQotzecWrUIN91BAO7Q5R38",
              "version": "23.8.0"
            }
          ],
          "received": 1693337923.817209,
          "event_id": "1ee15d3b4ce14169b285602bd9905841",
          "url": "https://sentry.io/api/0/projects/buildertrend/btnet-dotnet/events/1ee15d3b4ce14169b285602bd9905841/",
          "issue_url": "https://sentry.io/api/0/issues/4435517859/",
          "release": "313809-test",
          "level": "error",
          "_ref": 5790930,
          "environment": "Test",
          "message": "",
          "fingerprint": [
            "{{ default }}"
          ],
          "location": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
          "project": 5790930,
          "version": "7",
          "title": "System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.",
          "timestamp": 1693337923.333021,
          "user": {
            "data": {
              "other": {
                "Jobsite ID": "29984664",
                "Global User Id": "Chad Curtis (13062602) - ",
                "Portal Login Type": "Internal Users",
                "BTAdminLink": "https://test.buildertrend.net/btadmin/adminBuilders.aspx?builderid=21034",
                "Builder": "Mapstone Automation (21034)"
              }
            },
            "username": "Chad Curtis",
            "id": "13062602"
          },
          "issue_id": "4435517859",
          "metadata": {
            "in_app_frame_mix": "mixed",
            "type": "System.Data.SqlTypes.SqlNullValueException",
            "function": "string BTSqlString.get_Value()",
            "value": "Data is Null. This method or property cannot be called on Null values.",
            "filename": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
            "display_title_with_tree_label": false
          },
          "logger": "",
          "hashes": [
            "a20c9f1b520f71e0b3958e7018c48df4",
            "97b0f7eb2eb42ba3214865020600db77"
          ],
          "grouping_config": {
            "enhancements": "eJybzDRxc15qeXFJZU6qlZGBkbGugaGuoeEEAHJMCAM",
            "id": "newstyle:2023-01-11"
          },
          "_ref_version": 2,
          "contexts": {
            "Form Post Values": {
              "FormPostValues": "",
              "type": "Form Post Values"
            },
            "browser": {
              "name": "Firefox",
              "type": "browser",
              "version": "116.0"
            },
            "client_os": {
              "type": "os",
              "version": ">=10",
              "name": "Windows"
            },
            "os": {
              "raw_description": "Microsoft Windows 10.0.17763 ",
              "type": "os",
              "build": "17763",
              "name": "Windows",
              "version": "10"
            },
            "device": {
              "boot_time": "2023-08-26T08:51:30.9077038+00:00",
              "timezone": "Central Standard Time",
              "type": "device",
              "timezone_display_name": "(UTC-06:00) Central Time (US & Canada)"
            },
            "runtime": {
              "version": "4.8.4645.0",
              "name": ".NET Framework",
              "raw_description": ".NET Framework 4.8.4645.0",
              "type": "runtime"
            },
            "Custom Message": {
              "CustomMessage": "",
              "type": "Custom Message"
            },
            "app": {
              "app_start_time": "2023-08-29T19:30:25.8455158+00:00",
              "type": "app"
            },
            "ThreadPool Info": {
              "min_completion_port_threads": 4,
              "available_completion_port_threads": 1000,
              "type": "ThreadPool Info",
              "available_worker_threads": 32764,
              "max_worker_threads": 32767,
              "max_completion_port_threads": 1000,
              "min_worker_threads": 4
            },
            "Tracing Values": {
              "TraceId": "698dd75cc46f47a8",
              "type": "Tracing Values",
              "DataDogSpanId": "5224442723120816181",
              "DataDogTraceId": "5091332781619746480"
            },
            ".NET Framework": {
              ".NET Framework Client": "\"v4.8\", \"v4.0.0.0\"",
              ".NET Framework Full": "\"v4.8\"",
              "type": ".NET Framework",
              ".NET Framework ": "\"v2.0.50727\", \"v3.0\", \"v3.5\""
            },
            "Current Culture": {
              "name": "en-US",
              "calendar": "GregorianCalendar",
              "display_name": "English (United States)",
              "type": "Current Culture"
            },
            "Mobile App": {
              "type": "Mobile App",
              "MobileAppType": "",
              "NativeAppVersion": null
            },
            "Additional Exception Info": {
              "Source": "System.Data",
              "InnerExceptionNotes": null,
              "type": "Additional Exception Info"
            },
            "Request Items": {
              "IsWebAPI": true,
              "ConnectionStackCount": 0,
              "type": "Request Items"
            }
          },
          "exception": {
            "values": [
              {
                "raw_stacktrace": {
                  "frames": [
                    {
                      "raw_function": null,
                      "post_context": null,
                      "lock": null,
                      "errors": null,
                      "symbol_addr": null,
                      "filename": null,
                      "in_app": false,
                      "colno": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "abs_path": null,
                      "lineno": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "instruction_addr": "0x87",
                      "snapshot": null,
                      "addr_mode": null,
                      "platform": null,
                      "image_addr": null,
                      "symbol": null,
                      "pre_context": null,
                      "trust": null,
                      "context_line": null,
                      "vars": null,
                      "module": null
                    },
                    {
                      "context_line": null,
                      "snapshot": null,
                      "errors": null,
                      "addr_mode": null,
                      "post_context": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "data": null,
                      "abs_path": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "symbol": null,
                      "raw_function": null,
                      "colno": null,
                      "filename": null,
                      "in_app": false,
                      "module": null,
                      "platform": null,
                      "trust": null,
                      "image_addr": null,
                      "vars": null,
                      "lineno": null,
                      "instruction_addr": "0xf3",
                      "lock": null
                    },
                    {
                      "vars": null,
                      "data": null,
                      "lineno": null,
                      "module": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "trust": null,
                      "pre_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "snapshot": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "post_context": null,
                      "instruction_addr": "0x1a4",
                      "errors": null,
                      "context_line": null,
                      "addr_mode": null,
                      "colno": null,
                      "abs_path": null,
                      "raw_function": null,
                      "lock": null,
                      "in_app": false,
                      "platform": null,
                      "image_addr": null,
                      "filename": null
                    },
                    {
                      "post_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "lineno": null,
                      "in_app": false,
                      "data": null,
                      "abs_path": null,
                      "vars": null,
                      "module": null,
                      "colno": null,
                      "symbol": null,
                      "errors": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "lock": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "filename": null,
                      "pre_context": null,
                      "context_line": null,
                      "raw_function": null,
                      "image_addr": null,
                      "instruction_addr": "0x103",
                      "platform": null,
                      "trust": null,
                      "addr_mode": null
                    },
                    {
                      "platform": null,
                      "raw_function": null,
                      "symbol_addr": null,
                      "abs_path": null,
                      "filename": null,
                      "data": null,
                      "post_context": null,
                      "module": null,
                      "snapshot": null,
                      "in_app": false,
                      "colno": null,
                      "symbol": null,
                      "vars": null,
                      "instruction_addr": "0x91",
                      "pre_context": null,
                      "lock": null,
                      "lineno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "image_addr": null,
                      "context_line": null,
                      "trust": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "addr_mode": null,
                      "errors": null
                    },
                    {
                      "raw_function": null,
                      "image_addr": null,
                      "instruction_addr": "0x103",
                      "trust": null,
                      "context_line": null,
                      "filename": null,
                      "lineno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "errors": null,
                      "pre_context": null,
                      "in_app": false,
                      "symbol": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "colno": null,
                      "snapshot": null,
                      "module": null,
                      "platform": null,
                      "addr_mode": null,
                      "abs_path": null,
                      "symbol_addr": null,
                      "post_context": null,
                      "vars": null,
                      "lock": null
                    },
                    {
                      "lock": null,
                      "platform": null,
                      "module": null,
                      "errors": null,
                      "context_line": null,
                      "filename": null,
                      "lineno": null,
                      "in_app": false,
                      "vars": null,
                      "symbol_addr": null,
                      "raw_function": null,
                      "colno": null,
                      "trust": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "instruction_addr": "0x91",
                      "addr_mode": null,
                      "snapshot": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "symbol": null,
                      "pre_context": null,
                      "post_context": null,
                      "abs_path": null,
                      "data": null,
                      "image_addr": null
                    },
                    {
                      "pre_context": null,
                      "raw_function": null,
                      "trust": null,
                      "colno": null,
                      "lineno": null,
                      "vars": null,
                      "image_addr": null,
                      "symbol": null,
                      "context_line": null,
                      "snapshot": null,
                      "post_context": null,
                      "instruction_addr": "0x103",
                      "platform": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "data": null,
                      "lock": null,
                      "errors": null,
                      "filename": null,
                      "addr_mode": null,
                      "module": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "in_app": false,
                      "abs_path": null,
                      "symbol_addr": null
                    },
                    {
                      "context_line": null,
                      "colno": null,
                      "errors": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "snapshot": null,
                      "lock": null,
                      "platform": null,
                      "vars": null,
                      "symbol_addr": null,
                      "lineno": null,
                      "in_app": false,
                      "image_addr": null,
                      "abs_path": null,
                      "addr_mode": null,
                      "raw_function": null,
                      "module": null,
                      "pre_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "instruction_addr": "0x91",
                      "trust": null,
                      "data": null,
                      "symbol": null,
                      "filename": null,
                      "post_context": null
                    },
                    {
                      "addr_mode": null,
                      "snapshot": null,
                      "colno": null,
                      "lineno": null,
                      "trust": null,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "post_context": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "in_app": false,
                      "image_addr": null,
                      "lock": null,
                      "abs_path": null,
                      "module": null,
                      "instruction_addr": "0xab",
                      "data": null,
                      "symbol_addr": null,
                      "symbol": null,
                      "context_line": null,
                      "vars": null,
                      "pre_context": null,
                      "raw_function": null,
                      "platform": null,
                      "filename": null,
                      "errors": null
                    },
                    {
                      "module": null,
                      "lock": null,
                      "lineno": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "raw_function": null,
                      "addr_mode": null,
                      "instruction_addr": "0x0",
                      "vars": null,
                      "trust": null,
                      "colno": null,
                      "symbol": null,
                      "errors": null,
                      "context_line": null,
                      "data": null,
                      "platform": null,
                      "post_context": null,
                      "abs_path": null,
                      "image_addr": null,
                      "filename": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "snapshot": null
                    },
                    {
                      "in_app": true,
                      "platform": null,
                      "snapshot": null,
                      "raw_function": null,
                      "post_context": null,
                      "image_addr": null,
                      "lineno": 51,
                      "context_line": null,
                      "filename": "Controllers\\JobPickerController.post.cs",
                      "function": "async Task<BT_ServiceResponse<JobPickerJobsResponse>> JobPickerController.GetJobpickerData(JobPickerRequestData params)",
                      "abs_path": "Controllers\\JobPickerController.post.cs",
                      "data": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "trust": null,
                      "colno": 13,
                      "lock": null,
                      "symbol_addr": null,
                      "pre_context": null,
                      "vars": null,
                      "module": null,
                      "errors": null,
                      "symbol": null,
                      "addr_mode": null,
                      "instruction_addr": "0x108"
                    },
                    {
                      "platform": null,
                      "pre_context": null,
                      "lock": null,
                      "errors": null,
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\BusinessLogic.Managers\\Jobs\\BuilderJobPickerHandler.cs",
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "function": "async Task<JobPickerJobsResponse> BuilderJobPickerHandler.GetJobpickerDataAsync(JobPickerRequestData req, IBTBuilders builder, IGlobalUser currentUser, IEnumerable<IGlobalUser> users)",
                      "addr_mode": null,
                      "image_addr": null,
                      "symbol": null,
                      "snapshot": null,
                      "lineno": 143,
                      "in_app": true,
                      "post_context": null,
                      "symbol_addr": null,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\BusinessLogic.Managers\\Jobs\\BuilderJobPickerHandler.cs",
                      "context_line": null,
                      "data": null,
                      "instruction_addr": "0x16b",
                      "module": null,
                      "vars": null,
                      "trust": null,
                      "raw_function": null,
                      "colno": 13
                    },
                    {
                      "errors": null,
                      "addr_mode": null,
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\Handlers.Accounting\\Xero\\XeroInternal.cs",
                      "pre_context": null,
                      "post_context": null,
                      "trust": null,
                      "raw_function": null,
                      "platform": null,
                      "snapshot": null,
                      "image_addr": null,
                      "vars": null,
                      "module": null,
                      "lock": null,
                      "lineno": 43,
                      "package": "Handlers.Accounting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "data": null,
                      "symbol": null,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\Handlers.Accounting\\Xero\\XeroInternal.cs",
                      "function": "bool XeroInternal.IsConnected()",
                      "instruction_addr": "0xc",
                      "context_line": null,
                      "colno": 13,
                      "symbol_addr": null,
                      "in_app": true
                    },
                    {
                      "post_context": null,
                      "vars": null,
                      "abs_path": "DAL\\Entities\\Custom\\BuildersAccounting.entity.custom.vb",
                      "lock": null,
                      "data": null,
                      "lineno": 695,
                      "module": null,
                      "colno": 13,
                      "image_addr": null,
                      "function_id": "0x2407",
                      "errors": null,
                      "platform": null,
                      "instruction_addr": "0xd1",
                      "symbol": null,
                      "package": "BuilderTrend, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "in_app": true,
                      "function": "string BTBuildersAccounting.get_AccessToken()",
                      "snapshot": null,
                      "pre_context": null,
                      "raw_function": null,
                      "filename": "DAL\\Entities\\Custom\\BuildersAccounting.entity.custom.vb",
                      "symbol_addr": null,
                      "trust": null,
                      "context_line": null,
                      "addr_mode": "rel:0"
                    },
                    {
                      "colno": 17,
                      "function": "string BTSqlString.get_Value()",
                      "in_app": true,
                      "vars": null,
                      "snapshot": null,
                      "trust": null,
                      "data": null,
                      "context_line": null,
                      "platform": null,
                      "instruction_addr": "0x8",
                      "addr_mode": null,
                      "raw_function": null,
                      "package": "DAL.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "lineno": 22,
                      "image_addr": null,
                      "pre_context": null,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
                      "errors": null,
                      "lock": null,
                      "symbol": null,
                      "module": null,
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
                      "symbol_addr": null,
                      "post_context": null
                    },
                    {
                      "colno": null,
                      "trust": null,
                      "data": null,
                      "module": null,
                      "snapshot": null,
                      "vars": null,
                      "platform": null,
                      "in_app": false,
                      "function": "string SqlString.get_Value()",
                      "raw_function": null,
                      "package": "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "abs_path": null,
                      "instruction_addr": "0x14",
                      "lineno": null,
                      "lock": null,
                      "filename": null,
                      "errors": null,
                      "symbol": null,
                      "context_line": null,
                      "pre_context": null,
                      "post_context": null,
                      "image_addr": null,
                      "addr_mode": null,
                      "symbol_addr": null
                    }
                  ]
                },
                "value": "Data is Null. This method or property cannot be called on Null values.",
                "thread_id": 60,
                "stacktrace": {
                  "frames": [
                    {
                      "addr_mode": null,
                      "snapshot": null,
                      "symbol": null,
                      "module": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "vars": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "errors": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "abs_path": null,
                      "in_app": false,
                      "trust": null,
                      "filename": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "post_context": null,
                      "lock": null,
                      "raw_function": null,
                      "platform": null,
                      "image_addr": null,
                      "pre_context": null,
                      "instruction_addr": "0x87",
                      "colno": null,
                      "context_line": null
                    },
                    {
                      "pre_context": null,
                      "module": null,
                      "platform": null,
                      "colno": null,
                      "symbol_addr": null,
                      "addr_mode": null,
                      "context_line": null,
                      "in_app": false,
                      "symbol": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "lineno": null,
                      "abs_path": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "post_context": null,
                      "lock": null,
                      "image_addr": null,
                      "raw_function": null,
                      "filename": null,
                      "trust": null,
                      "snapshot": null,
                      "vars": null,
                      "instruction_addr": "0xf3",
                      "errors": null
                    },
                    {
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "symbol": null,
                      "addr_mode": null,
                      "symbol_addr": null,
                      "vars": null,
                      "filename": null,
                      "trust": null,
                      "image_addr": null,
                      "abs_path": null,
                      "raw_function": null,
                      "module": null,
                      "colno": null,
                      "lock": null,
                      "pre_context": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "post_context": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "instruction_addr": "0x1a4",
                      "errors": null,
                      "context_line": null,
                      "snapshot": null,
                      "lineno": null,
                      "platform": null
                    },
                    {
                      "vars": null,
                      "post_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "lineno": null,
                      "in_app": false,
                      "pre_context": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "image_addr": null,
                      "platform": null,
                      "snapshot": null,
                      "lock": null,
                      "filename": null,
                      "instruction_addr": "0x103",
                      "colno": null,
                      "raw_function": null,
                      "symbol_addr": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "context_line": null,
                      "symbol": null,
                      "abs_path": null,
                      "errors": null,
                      "trust": null,
                      "module": null,
                      "addr_mode": null
                    },
                    {
                      "lock": null,
                      "errors": null,
                      "context_line": null,
                      "post_context": null,
                      "pre_context": null,
                      "vars": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "image_addr": null,
                      "colno": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "in_app": false,
                      "symbol_addr": null,
                      "platform": null,
                      "addr_mode": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "lineno": null,
                      "trust": null,
                      "abs_path": null,
                      "raw_function": null,
                      "module": null,
                      "filename": null,
                      "snapshot": null,
                      "instruction_addr": "0x91",
                      "symbol": null
                    },
                    {
                      "snapshot": null,
                      "vars": null,
                      "in_app": false,
                      "lock": null,
                      "lineno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "addr_mode": null,
                      "module": null,
                      "colno": null,
                      "filename": null,
                      "raw_function": null,
                      "image_addr": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "post_context": null,
                      "instruction_addr": "0x103",
                      "symbol_addr": null,
                      "trust": null,
                      "errors": null,
                      "abs_path": null,
                      "platform": null,
                      "pre_context": null,
                      "symbol": null,
                      "context_line": null
                    },
                    {
                      "platform": null,
                      "filename": null,
                      "abs_path": null,
                      "pre_context": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "post_context": null,
                      "in_app": false,
                      "instruction_addr": "0x91",
                      "addr_mode": null,
                      "module": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "trust": null,
                      "raw_function": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "lock": null,
                      "lineno": null,
                      "context_line": null,
                      "vars": null,
                      "errors": null,
                      "colno": null,
                      "image_addr": null
                    },
                    {
                      "snapshot": null,
                      "lineno": null,
                      "lock": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "pre_context": null,
                      "addr_mode": null,
                      "module": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "symbol_addr": null,
                      "vars": null,
                      "context_line": null,
                      "post_context": null,
                      "abs_path": null,
                      "image_addr": null,
                      "raw_function": null,
                      "in_app": false,
                      "trust": null,
                      "colno": null,
                      "instruction_addr": "0x103",
                      "errors": null,
                      "filename": null,
                      "symbol": null,
                      "platform": null
                    },
                    {
                      "in_app": false,
                      "trust": null,
                      "errors": null,
                      "post_context": null,
                      "platform": null,
                      "snapshot": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "abs_path": null,
                      "addr_mode": null,
                      "symbol": null,
                      "vars": null,
                      "colno": null,
                      "lock": null,
                      "raw_function": null,
                      "pre_context": null,
                      "image_addr": null,
                      "instruction_addr": "0x91",
                      "symbol_addr": null,
                      "filename": null,
                      "module": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "lineno": null,
                      "context_line": null
                    },
                    {
                      "addr_mode": null,
                      "colno": null,
                      "symbol": null,
                      "vars": null,
                      "platform": null,
                      "image_addr": null,
                      "errors": null,
                      "lock": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "post_context": null,
                      "in_app": false,
                      "abs_path": null,
                      "pre_context": null,
                      "filename": null,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "instruction_addr": "0xab",
                      "symbol_addr": null,
                      "module": null,
                      "lineno": null,
                      "context_line": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "snapshot": null,
                      "raw_function": null,
                      "trust": null
                    },
                    {
                      "addr_mode": null,
                      "image_addr": null,
                      "platform": null,
                      "symbol": null,
                      "module": null,
                      "trust": null,
                      "abs_path": null,
                      "raw_function": null,
                      "snapshot": null,
                      "filename": null,
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "lineno": null,
                      "errors": null,
                      "colno": null,
                      "lock": null,
                      "instruction_addr": "0x0",
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "pre_context": null,
                      "symbol_addr": null,
                      "post_context": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "vars": null,
                      "context_line": null
                    },
                    {
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "errors": null,
                      "function": "async Task<BT_ServiceResponse<JobPickerJobsResponse>> JobPickerController.GetJobpickerData(JobPickerRequestData params)",
                      "platform": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "symbol_addr": null,
                      "raw_function": null,
                      "trust": null,
                      "image_addr": null,
                      "pre_context": null,
                      "abs_path": "Controllers\\JobPickerController.post.cs",
                      "symbol": null,
                      "lock": null,
                      "context_line": null,
                      "lineno": 51,
                      "filename": "Controllers\\JobPickerController.post.cs",
                      "colno": 13,
                      "module": null,
                      "vars": null,
                      "post_context": null,
                      "in_app": true,
                      "instruction_addr": "0x108"
                    },
                    {
                      "errors": null,
                      "colno": 13,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "function": "async Task<JobPickerJobsResponse> BuilderJobPickerHandler.GetJobpickerDataAsync(JobPickerRequestData req, IBTBuilders builder, IGlobalUser currentUser, IEnumerable<IGlobalUser> users)",
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\BusinessLogic.Managers\\Jobs\\BuilderJobPickerHandler.cs",
                      "context_line": null,
                      "lock": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "addr_mode": null,
                      "module": null,
                      "in_app": true,
                      "raw_function": null,
                      "platform": null,
                      "instruction_addr": "0x16b",
                      "image_addr": null,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\BusinessLogic.Managers\\Jobs\\BuilderJobPickerHandler.cs",
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "pre_context": null,
                      "lineno": 143,
                      "trust": null,
                      "post_context": null,
                      "snapshot": null,
                      "vars": null
                    },
                    {
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\Handlers.Accounting\\Xero\\XeroInternal.cs",
                      "vars": null,
                      "package": "Handlers.Accounting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "pre_context": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "post_context": null,
                      "symbol_addr": null,
                      "raw_function": null,
                      "colno": 13,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\Handlers.Accounting\\Xero\\XeroInternal.cs",
                      "in_app": true,
                      "image_addr": null,
                      "lock": null,
                      "function": "bool XeroInternal.IsConnected()",
                      "symbol": null,
                      "module": null,
                      "errors": null,
                      "context_line": null,
                      "lineno": 43,
                      "instruction_addr": "0xc",
                      "platform": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "trust": null
                    },
                    {
                      "platform": null,
                      "lineno": 695,
                      "post_context": null,
                      "function_id": "0x2407",
                      "package": "BuilderTrend, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "pre_context": null,
                      "in_app": true,
                      "context_line": null,
                      "symbol_addr": null,
                      "abs_path": "DAL\\Entities\\Custom\\BuildersAccounting.entity.custom.vb",
                      "lock": null,
                      "symbol": null,
                      "addr_mode": "rel:0",
                      "image_addr": null,
                      "vars": null,
                      "trust": null,
                      "function": "string BTBuildersAccounting.get_AccessToken()",
                      "raw_function": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "snapshot": null,
                      "errors": null,
                      "colno": 13,
                      "instruction_addr": "0xd1",
                      "module": null,
                      "filename": "DAL\\Entities\\Custom\\BuildersAccounting.entity.custom.vb"
                    },
                    {
                      "errors": null,
                      "post_context": null,
                      "context_line": null,
                      "trust": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "symbol": null,
                      "raw_function": null,
                      "abs_path": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
                      "platform": null,
                      "module": null,
                      "instruction_addr": "0x8",
                      "image_addr": null,
                      "lineno": 22,
                      "colno": 17,
                      "pre_context": null,
                      "package": "DAL.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "filename": "C:\\adoBuild1\\_work\\3\\s\\DAL.Core\\SqlProperties\\BTSqlString.cs",
                      "lock": null,
                      "function": "string BTSqlString.get_Value()",
                      "vars": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "in_app": true
                    },
                    {
                      "symbol": null,
                      "instruction_addr": "0x14",
                      "module": null,
                      "context_line": null,
                      "function": "string SqlString.get_Value()",
                      "colno": null,
                      "pre_context": null,
                      "image_addr": null,
                      "trust": null,
                      "errors": null,
                      "filename": null,
                      "data": {
                        "symbolicator_status": "missing"
                      },
                      "platform": null,
                      "lock": null,
                      "vars": null,
                      "package": "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "post_context": null,
                      "addr_mode": null,
                      "abs_path": null,
                      "raw_function": null,
                      "snapshot": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "in_app": false
                    }
                  ]
                },
                "module": "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                "type": "System.Data.SqlTypes.SqlNullValueException"
              }
            ]
          },
          "tags": [
            [
              "BT-Employee",
              "Chad Curtis"
            ],
            [
              "app-type",
              "WebApp"
            ],
            [
              "browser",
              "Firefox 116.0"
            ],
            [
              "browser.name",
              "Firefox"
            ],
            [
              "builder-id",
              "21034"
            ],
            [
              "builder-name",
              "Mapstone Automation"
            ],
            [
              "client_os",
              "Windows >=10"
            ],
            [
              "client_os.name",
              "Windows"
            ],
            [
              "environment",
              "Test"
            ],
            [
              "exception-class",
              "System.Data.SqlTypes.SqlNullValueException"
            ],
            [
              "level",
              "error"
            ],
            [
              "os",
              "Windows 10"
            ],
            [
              "os.name",
              "Windows"
            ],
            [
              "runtime",
              ".NET Framework 4.8.4645.0"
            ],
            [
              "runtime.name",
              ".NET Framework"
            ],
            [
              "release",
              "313809-test"
            ],
            [
              "user",
              "id:13062602"
            ],
            [
              "server-ip",
              "35.184.88.245"
            ],
            [
              "server_name",
              "TEST-WEB-C080"
            ],
            [
              "site-name",
              "test.buildertrend.net"
            ],
            [
              "transaction-id",
              "e5922855-d1d0-48a3-8ff2-afdbc37024e0"
            ],
            [
              "url",
              "https://test.buildertrend.net/api/jobpicker/GetJobPickerData"
            ]
          ],
          "request": {
            "url": "https://test.buildertrend.net/api/jobpicker/GetJobPickerData",
            "data": null,
            "fragment": null,
            "method": "POST",
            "cookies": null,
            "query_string": [],
            "api_target": null,
            "inferred_content_type": "application/json",
            "env": null,
            "headers": [
              [
                "Accept",
                "*/*"
              ],
              [
                "Accept-Encoding",
                "gzip, deflate, br"
              ],
              [
                "Accept-Language",
                "en-US,en;q=0.5"
              ],
              [
                "Alt-Used",
                "test.buildertrend.net"
              ],
              [
                "Baggage",
                "sentry-environment=test.buildertrend.net,sentry-release=313780-test,sentry-public_key=90ea83bd365f425fad8c55d22a905a58,sentry-trace_id=dadcf8b83ecb453bb1371b72659e3ab6,sentry-sample_rate=0.0001"
              ],
              [
                "Content-Length",
                "252"
              ],
              [
                "Content-Type",
                "application/json"
              ],
              [
                "Host",
                "test.buildertrend.net"
              ],
              [
                "Origin",
                "https://test.buildertrend.net"
              ],
              [
                "Portaltype",
                "1"
              ],
              [
                "Priority",
                "u=4"
              ],
              [
                "Referer",
                "https://test.buildertrend.net/summaryGrid.aspx"
              ],
              [
                "Sec-Fetch-Dest",
                "empty"
              ],
              [
                "Sec-Fetch-Mode",
                "cors"
              ],
              [
                "Sec-Fetch-Site",
                "same-origin"
              ],
              [
                "Sentry-Trace",
                "dadcf8b83ecb453bb1371b72659e3ab6-ab3863bb5ececc46-0"
              ],
              [
                "User-Agent",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"
              ],
              [
                "Via",
                "1.1 google"
              ],
              [
                "X-Client-Geo-City",
                "Omaha"
              ],
              [
                "X-Client-Geo-Latlong",
                "41.256537,-95.934503"
              ],
              [
                "X-Client-Geo-Region",
                "US"
              ],
              [
                "X-Client-Geo-Subregion",
                "USNE"
              ],
              [
                "X-Client-Ip",
                "35.184.88.245"
              ],
              [
                "X-Cloud-Trace-Context",
                "8c7930cde39627bb5cec1ab65d19c068/6068473722367599689"
              ],
              [
                "X-Datadog-Origin",
                "rum"
              ],
              [
                "X-Datadog-Parent-Id",
                "5199143763436369295"
              ],
              [
                "X-Datadog-Sampling-Priority",
                "1"
              ],
              [
                "X-Datadog-Trace-Id",
                "5091332781619746480"
              ],
              [
                "X-Forwarded-For",
                "35.184.88.245,34.96.120.197"
              ],
              [
                "X-Forwarded-Proto",
                "https"
              ]
            ]
          },
          "type": "error"
        }
      },
      "installation": {
        "uuid": "dbb4da9c-e292-48a8-9c4c-07f3f0bcce03"
      }
    },
    "resource": {
      "type": "cloud_run_revision",
      "labels": {
        "project_id": "clear-network-397314",
        "location": "us-central1",
        "revision_name": "sentry-test3-00023-wif",
        "service_name": "sentry-test3",
        "configuration_name": "sentry-test3"
      }
    },
    "timestamp": "2023-08-29T19:39:04.818921Z",
    "labels": {
      "goog-managed-by": "cloudfunctions",
      "instanceId": "00e6760073f65dc8d29f287b040546f586e208462038af9fa76113a1ec657449fca4113dfa7687ee988d748fec3d55df3c8c8c2e76bdff701a9e1c93840c427b2687"
    },
    "logName": "projects/clear-network-397314/logs/run.googleapis.com%2Fstdout",
    "receiveTimestamp": "2023-08-29T19:39:04.956104658Z"
  }
