const faker = {
    "insertId": "64ee5b0e0007924a9d5f144e",
    "jsonPayload": {
      "data": {
        "event": {
          "received": 1693342462.53133,
          "version": "7",
          "message": "",
          "request": {
            "api_target": null,
            "headers": [
              [
                "Accept",
                "*/*"
              ],
              [
                "Accept-Encoding",
                "gzip, deflate, br"
              ],
              [
                "Accept-Language",
                "en-US,en;q=0.9"
              ],
              [
                "Cache-Control",
                "no-cache"
              ],
              [
                "Content-Length",
                "908"
              ],
              [
                "Content-Type",
                "application/json"
              ],
              [
                "Host",
                "test.buildertrend.net"
              ],
              [
                "Origin",
                "https://test.buildertrend.net"
              ],
              [
                "Portaltype",
                "1"
              ],
              [
                "Pragma",
                "no-cache"
              ],
              [
                "Referer",
                "https://test.buildertrend.net/POs/Worksheet.aspx"
              ],
              [
                "Sec-Ch-Ua",
                "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\""
              ],
              [
                "Sec-Ch-Ua-Mobile",
                "?0"
              ],
              [
                "Sec-Ch-Ua-Platform",
                "\"Windows\""
              ],
              [
                "Sec-Fetch-Dest",
                "empty"
              ],
              [
                "Sec-Fetch-Mode",
                "cors"
              ],
              [
                "Sec-Fetch-Site",
                "same-origin"
              ],
              [
                "User-Agent",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
              ],
              [
                "Via",
                "1.1 google"
              ],
              [
                "X-Client-Geo-City",
                "Omaha"
              ],
              [
                "X-Client-Geo-Latlong",
                "41.256537,-95.934503"
              ],
              [
                "X-Client-Geo-Region",
                "US"
              ],
              [
                "X-Client-Geo-Subregion",
                "USNE"
              ],
              [
                "X-Client-Ip",
                "35.184.88.245"
              ],
              [
                "X-Cloud-Trace-Context",
                "5a16adc3c7928523f61b813e41f43163/7565461765718168671"
              ],
              [
                "X-Datadog-Origin",
                "rum"
              ],
              [
                "X-Datadog-Parent-Id",
                "2215096718012459913"
              ],
              [
                "X-Datadog-Sampling-Priority",
                "1"
              ],
              [
                "X-Datadog-Trace-Id",
                "2962336472897554516"
              ],
              [
                "X-Forwarded-For",
                "35.184.88.245,34.96.120.197"
              ],
              [
                "X-Forwarded-Proto",
                "https"
              ]
            ],
            "query_string": [
              [
                "jobId",
                "30078956"
              ]
            ],
            "method": "POST",
            "data": null,
            "fragment": null,
            "env": null,
            "inferred_content_type": "application/json",
            "url": "https://test.buildertrend.net/api/Payments/",
            "cookies": null
          },
          "environment": "Test",
          "grouping_config": {
            "id": "newstyle:2023-01-11",
            "enhancements": "eJybzDRxc15qeXFJZU6qlZGBkbGugaGuoeEEAHJMCAM"
          },
          "ingest_path": [
            {
              "public_key": "XE7QiyuNlja9PZ7I9qJlwQotzecWrUIN91BAO7Q5R38",
              "version": "23.8.0"
            }
          ],
          "_ref_version": 2,
          "contexts": {
            "client_os": {
              "type": "os",
              "name": "Windows"
            },
            "Request Items": {
              "ConnectionStackCount": 0,
              "type": "Request Items",
              "IsWebAPI": true
            },
            "Current Culture": {
              "calendar": "GregorianCalendar",
              "type": "Current Culture",
              "display_name": "English (United States)",
              "name": "en-US"
            },
            "browser": {
              "name": "Google Chrome",
              "type": "browser",
              "version": "116"
            },
            "Custom Message": {
              "CustomMessage": "",
              "type": "Custom Message"
            },
            "ThreadPool Info": {
              "type": "ThreadPool Info",
              "min_completion_port_threads": 4,
              "max_completion_port_threads": 1000,
              "min_worker_threads": 4,
              "max_worker_threads": 32767,
              "available_completion_port_threads": 1000,
              "available_worker_threads": 32766
            },
            "runtime": {
              "raw_description": ".NET Framework 4.8.4645.0",
              "version": "4.8.4645.0",
              "name": ".NET Framework",
              "type": "runtime"
            },
            "app": {
              "type": "app",
              "app_start_time": "2023-08-29T20:19:35.5452764+00:00"
            },
            "device": {
              "type": "device",
              "timezone_display_name": "(UTC-06:00) Central Time (US & Canada)",
              "boot_time": "2023-08-15T08:47:36.1710196+00:00",
              "timezone": "Central Standard Time"
            },
            "Tracing Values": {
              "type": "Tracing Values",
              "DataDogSpanId": "7094023025336553119",
              "TraceId": "5cddf5abc4725a30",
              "DataDogTraceId": "2962336472897554516"
            },
            "Form Post Values": {
              "type": "Form Post Values",
              "FormPostValues": ""
            },
            "Additional Exception Info": {
              "InnerExceptionNotes": null,
              "Source": "BusinessLogic.Managers",
              "type": "Additional Exception Info"
            },
            "os": {
              "raw_description": "Microsoft Windows 10.0.17763 ",
              "name": "Windows",
              "type": "os",
              "version": "10",
              "build": "17763"
            },
            "Mobile App": {
              "NativeAppVersion": null,
              "type": "Mobile App",
              "MobileAppType": ""
            },
            ".NET Framework": {
              ".NET Framework Full": "\"v4.8\"",
              ".NET Framework ": "\"v2.0.50727\", \"v3.0\", \"v3.5\"",
              ".NET Framework Client": "\"v4.8\", \"v4.0.0.0\"",
              "type": ".NET Framework"
            }
          },
          "platform": "csharp",
          "timestamp": 1693342462.510752,
          "fingerprint": [
            "{{ default }}"
          ],
          "url": "https://sentry.io/api/0/projects/buildertrend/btnet-dotnet/events/9984f6faec874f929c321635751046c3/",
          "logger": "",
          "event_id": "9984f6faec874f929c321635751046c3",
          "type": "error",
          "user": {
            "data": {
              "other": {
                "Jobsite ID": "30078956",
                "Global User Id": "Corbin Kems (29723909) - ",
                "Portal Login Type": "Internal Users",
                "BTAdminLink": "https://test.buildertrend.net/btadmin/adminBuilders.aspx?builderid=4833",
                "Builder": "Tajo One Inc  -  LIC#0072355/0080525/0071786 (4833)"
              }
            },
            "id": "29723909",
            "username": "Corbin Kems"
          },
          "exception": {
            "values": [
              {
                "raw_stacktrace": {
                  "frames": [
                    {
                      "instruction_addr": "0x87",
                      "errors": null,
                      "raw_function": null,
                      "image_addr": null,
                      "context_line": null,
                      "pre_context": null,
                      "vars": null,
                      "post_context": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "data": null,
                      "platform": null,
                      "in_app": false,
                      "addr_mode": null,
                      "abs_path": null,
                      "lock": null,
                      "symbol": null,
                      "colno": null,
                      "trust": null,
                      "filename": null,
                      "snapshot": null,
                      "lineno": null,
                      "module": null,
                      "symbol_addr": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                    },
                    {
                      "context_line": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "errors": null,
                      "lineno": null,
                      "vars": null,
                      "lock": null,
                      "image_addr": null,
                      "data": null,
                      "platform": null,
                      "pre_context": null,
                      "in_app": false,
                      "instruction_addr": "0xf3",
                      "symbol_addr": null,
                      "filename": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "colno": null,
                      "abs_path": null,
                      "raw_function": null,
                      "module": null,
                      "post_context": null,
                      "symbol": null,
                      "trust": null,
                      "addr_mode": null,
                      "snapshot": null
                    },
                    {
                      "post_context": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "in_app": false,
                      "symbol": null,
                      "addr_mode": null,
                      "errors": null,
                      "lock": null,
                      "pre_context": null,
                      "context_line": null,
                      "raw_function": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "module": null,
                      "image_addr": null,
                      "trust": null,
                      "platform": null,
                      "snapshot": null,
                      "colno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "abs_path": null,
                      "vars": null,
                      "instruction_addr": "0x1a4",
                      "filename": null,
                      "data": null
                    },
                    {
                      "vars": null,
                      "in_app": false,
                      "platform": null,
                      "trust": null,
                      "symbol": null,
                      "module": null,
                      "symbol_addr": null,
                      "lock": null,
                      "raw_function": null,
                      "colno": null,
                      "post_context": null,
                      "abs_path": null,
                      "errors": null,
                      "addr_mode": null,
                      "filename": null,
                      "snapshot": null,
                      "pre_context": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "context_line": null,
                      "lineno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "image_addr": null,
                      "instruction_addr": "0x103"
                    },
                    {
                      "symbol": null,
                      "platform": null,
                      "raw_function": null,
                      "module": null,
                      "vars": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "trust": null,
                      "lock": null,
                      "instruction_addr": "0x91",
                      "errors": null,
                      "colno": null,
                      "filename": null,
                      "post_context": null,
                      "data": null,
                      "image_addr": null,
                      "symbol_addr": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "in_app": false,
                      "snapshot": null,
                      "addr_mode": null,
                      "context_line": null,
                      "pre_context": null,
                      "abs_path": null,
                      "lineno": null
                    },
                    {
                      "abs_path": null,
                      "post_context": null,
                      "module": null,
                      "filename": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "addr_mode": null,
                      "pre_context": null,
                      "platform": null,
                      "instruction_addr": "0x103",
                      "raw_function": null,
                      "in_app": false,
                      "data": null,
                      "image_addr": null,
                      "lock": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "symbol": null,
                      "errors": null,
                      "vars": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "trust": null,
                      "colno": null,
                      "context_line": null
                    },
                    {
                      "snapshot": null,
                      "context_line": null,
                      "colno": null,
                      "data": null,
                      "module": null,
                      "raw_function": null,
                      "symbol": null,
                      "vars": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "in_app": false,
                      "addr_mode": null,
                      "image_addr": null,
                      "platform": null,
                      "lineno": null,
                      "lock": null,
                      "abs_path": null,
                      "filename": null,
                      "trust": null,
                      "pre_context": null,
                      "errors": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "post_context": null,
                      "instruction_addr": "0x91",
                      "symbol_addr": null
                    },
                    {
                      "platform": null,
                      "post_context": null,
                      "raw_function": null,
                      "abs_path": null,
                      "errors": null,
                      "data": null,
                      "in_app": false,
                      "image_addr": null,
                      "context_line": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "lineno": null,
                      "colno": null,
                      "lock": null,
                      "trust": null,
                      "instruction_addr": "0x103",
                      "addr_mode": null,
                      "module": null,
                      "symbol_addr": null,
                      "symbol": null,
                      "filename": null,
                      "vars": null,
                      "pre_context": null,
                      "snapshot": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                    },
                    {
                      "pre_context": null,
                      "raw_function": null,
                      "image_addr": null,
                      "data": null,
                      "context_line": null,
                      "vars": null,
                      "lock": null,
                      "symbol": null,
                      "in_app": false,
                      "addr_mode": null,
                      "colno": null,
                      "errors": null,
                      "lineno": null,
                      "trust": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "symbol_addr": null,
                      "post_context": null,
                      "module": null,
                      "abs_path": null,
                      "platform": null,
                      "snapshot": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "filename": null,
                      "instruction_addr": "0x91"
                    },
                    {
                      "lineno": null,
                      "trust": null,
                      "vars": null,
                      "abs_path": null,
                      "data": null,
                      "in_app": false,
                      "pre_context": null,
                      "raw_function": null,
                      "module": null,
                      "addr_mode": null,
                      "colno": null,
                      "instruction_addr": "0xab",
                      "snapshot": null,
                      "filename": null,
                      "errors": null,
                      "symbol": null,
                      "platform": null,
                      "image_addr": null,
                      "post_context": null,
                      "symbol_addr": null,
                      "context_line": null,
                      "lock": null,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
                    },
                    {
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "abs_path": null,
                      "addr_mode": null,
                      "symbol": null,
                      "platform": null,
                      "errors": null,
                      "pre_context": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "trust": null,
                      "lock": null,
                      "post_context": null,
                      "image_addr": null,
                      "raw_function": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "module": null,
                      "filename": null,
                      "data": null,
                      "in_app": false,
                      "context_line": null,
                      "instruction_addr": "0x0",
                      "colno": null,
                      "vars": null,
                      "snapshot": null
                    },
                    {
                      "filename": "Controllers\\PaymentsController.post.cs",
                      "post_context": null,
                      "raw_function": null,
                      "abs_path": "Controllers\\PaymentsController.post.cs",
                      "lock": null,
                      "symbol_addr": null,
                      "colno": 17,
                      "in_app": true,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "addr_mode": null,
                      "vars": null,
                      "errors": null,
                      "data": null,
                      "instruction_addr": "0xd9",
                      "image_addr": null,
                      "symbol": null,
                      "function": "async Task<BT_ServiceResponse<CreateOwnerPaymentResponse>> PaymentsController.CreateOwnerPaymentAsync(EditOwnerPaymentRequest data, int? jobId)",
                      "platform": null,
                      "snapshot": null,
                      "module": null,
                      "trust": null,
                      "lineno": 40,
                      "context_line": null,
                      "pre_context": null
                    },
                    {
                      "context_line": null,
                      "platform": null,
                      "addr_mode": null,
                      "pre_context": null,
                      "image_addr": null,
                      "snapshot": null,
                      "colno": 17,
                      "function": "async Task<CreateOwnerPaymentResponse> PaymentsController.CreateOwnerPaymentInternalAsync(EditOwnerPaymentRequest data)",
                      "symbol": null,
                      "errors": null,
                      "lock": null,
                      "filename": "Controllers\\PaymentsController.cs",
                      "data": null,
                      "in_app": true,
                      "vars": null,
                      "abs_path": "Controllers\\PaymentsController.cs",
                      "instruction_addr": "0x3b8",
                      "module": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "post_context": null,
                      "symbol_addr": null,
                      "raw_function": null,
                      "trust": null,
                      "lineno": 1518
                    },
                    {
                      "lock": null,
                      "abs_path": "Controllers\\PaymentsController.cs",
                      "instruction_addr": "0xff",
                      "module": null,
                      "lineno": 1467,
                      "errors": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "colno": 13,
                      "vars": null,
                      "image_addr": null,
                      "addr_mode": null,
                      "context_line": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "function": "void PaymentsController.SetLineItemUnitCost<TEntity>(List<LineItem> lineItems, LineItemType type, Func<LineItem, long?> idSelector, int builderId, int jobId, bool? isCostPlus)",
                      "filename": "Controllers\\PaymentsController.cs",
                      "data": null,
                      "symbol": null,
                      "in_app": true,
                      "trust": null,
                      "raw_function": null,
                      "snapshot": null,
                      "post_context": null,
                      "platform": null
                    },
                    {
                      "function": "void OwnerInvoicesManager.SetLineItemsUnitCost(Dictionary<LineItem, IMarkupLineItem> lineItemDict, LineItemType lineItemType, bool? isCostPlus)",
                      "addr_mode": null,
                      "snapshot": null,
                      "colno": 17,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "instruction_addr": "0x2b",
                      "vars": null,
                      "platform": null,
                      "symbol_addr": null,
                      "data": null,
                      "pre_context": null,
                      "abs_path": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "lock": null,
                      "symbol": null,
                      "raw_function": null,
                      "filename": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "image_addr": null,
                      "lineno": 2862,
                      "post_context": null,
                      "context_line": null,
                      "in_app": true,
                      "module": null,
                      "trust": null,
                      "errors": null
                    },
                    {
                      "lineno": 2903,
                      "symbol": null,
                      "abs_path": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "context_line": null,
                      "data": null,
                      "image_addr": null,
                      "instruction_addr": "0x16a",
                      "raw_function": null,
                      "function": "void OwnerInvoicesManager.SetLineItemUnitCost(LineItem invoiceLineItem, IMarkupLineItem markupLineItem, LineItemType lineItemType, bool? isCostPlus)",
                      "errors": null,
                      "platform": null,
                      "pre_context": null,
                      "vars": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "module": null,
                      "filename": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "in_app": true,
                      "colno": 13,
                      "post_context": null,
                      "trust": null,
                      "symbol_addr": null,
                      "lock": null
                    }
                  ]
                },
                "stacktrace": {
                  "frames": [
                    {
                      "image_addr": null,
                      "abs_path": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "lock": null,
                      "colno": null,
                      "instruction_addr": "0x87",
                      "context_line": null,
                      "post_context": null,
                      "filename": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "addr_mode": null,
                      "vars": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "snapshot": null,
                      "lineno": null,
                      "in_app": false,
                      "platform": null,
                      "pre_context": null,
                      "errors": null,
                      "raw_function": null,
                      "module": null,
                      "trust": null
                    },
                    {
                      "abs_path": null,
                      "vars": null,
                      "module": null,
                      "trust": null,
                      "snapshot": null,
                      "lock": null,
                      "instruction_addr": "0xf3",
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "addr_mode": null,
                      "in_app": false,
                      "post_context": null,
                      "filename": null,
                      "pre_context": null,
                      "context_line": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "raw_function": null,
                      "errors": null,
                      "lineno": null,
                      "image_addr": null,
                      "symbol_addr": null,
                      "symbol": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "colno": null,
                      "platform": null
                    },
                    {
                      "image_addr": null,
                      "lineno": null,
                      "lock": null,
                      "symbol_addr": null,
                      "instruction_addr": "0x1a4",
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "pre_context": null,
                      "platform": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "filename": null,
                      "module": null,
                      "post_context": null,
                      "abs_path": null,
                      "colno": null,
                      "addr_mode": null,
                      "in_app": false,
                      "symbol": null,
                      "snapshot": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "context_line": null,
                      "vars": null,
                      "raw_function": null,
                      "errors": null,
                      "trust": null
                    },
                    {
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "pre_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "module": null,
                      "addr_mode": null,
                      "vars": null,
                      "in_app": false,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "platform": null,
                      "context_line": null,
                      "symbol": null,
                      "raw_function": null,
                      "trust": null,
                      "post_context": null,
                      "snapshot": null,
                      "lineno": null,
                      "filename": null,
                      "symbol_addr": null,
                      "colno": null,
                      "abs_path": null,
                      "instruction_addr": "0x103",
                      "errors": null,
                      "lock": null,
                      "image_addr": null
                    },
                    {
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "module": null,
                      "snapshot": null,
                      "platform": null,
                      "lock": null,
                      "vars": null,
                      "colno": null,
                      "in_app": false,
                      "trust": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "abs_path": null,
                      "lineno": null,
                      "instruction_addr": "0x91",
                      "symbol": null,
                      "filename": null,
                      "raw_function": null,
                      "post_context": null,
                      "context_line": null,
                      "image_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "symbol_addr": null,
                      "errors": null,
                      "pre_context": null,
                      "addr_mode": null
                    },
                    {
                      "abs_path": null,
                      "image_addr": null,
                      "filename": null,
                      "symbol_addr": null,
                      "platform": null,
                      "trust": null,
                      "colno": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "errors": null,
                      "post_context": null,
                      "pre_context": null,
                      "vars": null,
                      "context_line": null,
                      "snapshot": null,
                      "instruction_addr": "0x103",
                      "addr_mode": null,
                      "lock": null,
                      "raw_function": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "module": null,
                      "lineno": null,
                      "symbol": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      }
                    },
                    {
                      "snapshot": null,
                      "lock": null,
                      "pre_context": null,
                      "platform": null,
                      "module": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "vars": null,
                      "symbol": null,
                      "lineno": null,
                      "trust": null,
                      "context_line": null,
                      "image_addr": null,
                      "instruction_addr": "0x91",
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "filename": null,
                      "in_app": false,
                      "abs_path": null,
                      "colno": null,
                      "addr_mode": null,
                      "raw_function": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "post_context": null,
                      "symbol_addr": null,
                      "errors": null
                    },
                    {
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "abs_path": null,
                      "module": null,
                      "image_addr": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "raw_function": null,
                      "filename": null,
                      "trust": null,
                      "symbol_addr": null,
                      "pre_context": null,
                      "errors": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "context_line": null,
                      "instruction_addr": "0x103",
                      "post_context": null,
                      "colno": null,
                      "vars": null,
                      "addr_mode": null,
                      "platform": null,
                      "snapshot": null,
                      "symbol": null,
                      "lineno": null,
                      "lock": null
                    },
                    {
                      "post_context": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "addr_mode": null,
                      "symbol": null,
                      "trust": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "image_addr": null,
                      "context_line": null,
                      "in_app": false,
                      "raw_function": null,
                      "instruction_addr": "0x91",
                      "vars": null,
                      "lineno": null,
                      "snapshot": null,
                      "platform": null,
                      "module": null,
                      "pre_context": null,
                      "colno": null,
                      "filename": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "errors": null,
                      "abs_path": null,
                      "symbol_addr": null,
                      "lock": null
                    },
                    {
                      "errors": null,
                      "in_app": false,
                      "filename": null,
                      "platform": null,
                      "instruction_addr": "0xab",
                      "context_line": null,
                      "post_context": null,
                      "module": null,
                      "raw_function": null,
                      "abs_path": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "pre_context": null,
                      "vars": null,
                      "lineno": null,
                      "trust": null,
                      "image_addr": null,
                      "lock": null,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "snapshot": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "colno": null,
                      "addr_mode": null
                    },
                    {
                      "context_line": null,
                      "symbol": null,
                      "image_addr": null,
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "addr_mode": null,
                      "pre_context": null,
                      "post_context": null,
                      "abs_path": null,
                      "filename": null,
                      "instruction_addr": "0x0",
                      "trust": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "snapshot": null,
                      "colno": null,
                      "module": null,
                      "errors": null,
                      "raw_function": null,
                      "lock": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "symbol_addr": null,
                      "in_app": false,
                      "lineno": null,
                      "platform": null,
                      "vars": null
                    },
                    {
                      "snapshot": null,
                      "symbol_addr": null,
                      "pre_context": null,
                      "trust": null,
                      "symbol": null,
                      "vars": null,
                      "lineno": 40,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "post_context": null,
                      "lock": null,
                      "raw_function": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "image_addr": null,
                      "filename": "Controllers\\PaymentsController.post.cs",
                      "errors": null,
                      "platform": null,
                      "in_app": true,
                      "instruction_addr": "0xd9",
                      "colno": 17,
                      "addr_mode": null,
                      "module": null,
                      "abs_path": "Controllers\\PaymentsController.post.cs",
                      "context_line": null,
                      "function": "async Task<BT_ServiceResponse<CreateOwnerPaymentResponse>> PaymentsController.CreateOwnerPaymentAsync(EditOwnerPaymentRequest data, int? jobId)"
                    },
                    {
                      "module": null,
                      "addr_mode": null,
                      "post_context": null,
                      "snapshot": null,
                      "in_app": true,
                      "symbol_addr": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "abs_path": "Controllers\\PaymentsController.cs",
                      "colno": 17,
                      "lineno": 1518,
                      "pre_context": null,
                      "lock": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "image_addr": null,
                      "vars": null,
                      "function": "async Task<CreateOwnerPaymentResponse> PaymentsController.CreateOwnerPaymentInternalAsync(EditOwnerPaymentRequest data)",
                      "errors": null,
                      "context_line": null,
                      "filename": "Controllers\\PaymentsController.cs",
                      "instruction_addr": "0x3b8",
                      "raw_function": null,
                      "symbol": null,
                      "trust": null,
                      "platform": null
                    },
                    {
                      "lock": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "function": "void PaymentsController.SetLineItemUnitCost<TEntity>(List<LineItem> lineItems, LineItemType type, Func<LineItem, long?> idSelector, int builderId, int jobId, bool? isCostPlus)",
                      "vars": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "errors": null,
                      "instruction_addr": "0xff",
                      "trust": null,
                      "platform": null,
                      "symbol": null,
                      "lineno": 1467,
                      "image_addr": null,
                      "in_app": true,
                      "addr_mode": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "module": null,
                      "colno": 13,
                      "post_context": null,
                      "context_line": null,
                      "raw_function": null,
                      "snapshot": null,
                      "filename": "Controllers\\PaymentsController.cs",
                      "abs_path": "Controllers\\PaymentsController.cs"
                    },
                    {
                      "function": "void OwnerInvoicesManager.SetLineItemsUnitCost(Dictionary<LineItem, IMarkupLineItem> lineItemDict, LineItemType lineItemType, bool? isCostPlus)",
                      "lock": null,
                      "trust": null,
                      "vars": null,
                      "lineno": 2862,
                      "context_line": null,
                      "symbol_addr": null,
                      "filename": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "image_addr": null,
                      "abs_path": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "addr_mode": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "symbol": null,
                      "pre_context": null,
                      "colno": 17,
                      "errors": null,
                      "in_app": true,
                      "post_context": null,
                      "module": null,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "snapshot": null,
                      "platform": null,
                      "raw_function": null,
                      "instruction_addr": "0x2b"
                    },
                    {
                      "addr_mode": null,
                      "post_context": null,
                      "context_line": null,
                      "abs_path": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "instruction_addr": "0x16a",
                      "symbol": null,
                      "pre_context": null,
                      "colno": 13,
                      "lock": null,
                      "module": null,
                      "image_addr": null,
                      "trust": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "in_app": true,
                      "function": "void OwnerInvoicesManager.SetLineItemUnitCost(LineItem invoiceLineItem, IMarkupLineItem markupLineItem, LineItemType lineItemType, bool? isCostPlus)",
                      "errors": null,
                      "platform": null,
                      "raw_function": null,
                      "filename": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
                      "vars": null,
                      "symbol_addr": null,
                      "lineno": 2903,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "snapshot": null
                    }
                  ]
                },
                "value": "Unknown markup column",
                "thread_id": 52,
                "module": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                "type": "System.NotImplementedException"
              }
            ]
          },
          "issue_url": "https://sentry.io/api/0/issues/4435706223/",
          "title": "System.NotImplementedException: Unknown markup column",
          "_ref": 5790930,
          "sdk": {
            "name": "sentry.dotnet",
            "version": "3.25.0",
            "integrations": null,
            "packages": [
              {
                "version": "3.25.0",
                "name": "nuget:Sentry.AspNet"
              },
              {
                "name": "nuget:sentry.dotnet",
                "version": "3.25.0"
              }
            ]
          },
          "nodestore_insert": 1693342464.944509,
          "key_id": "1682840",
          "issue_id": "4435706223",
          "location": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs",
          "tags": [
            [
              "BT-Employee",
              "Corbin Kems"
            ],
            [
              "app-type",
              "WebApp"
            ],
            [
              "browser",
              "Google Chrome 116"
            ],
            [
              "browser.name",
              "Google Chrome"
            ],
            [
              "builder-id",
              "4833"
            ],
            [
              "builder-name",
              "Tajo One Inc  -  LIC#0072355/0080525/0071786"
            ],
            [
              "client_os.name",
              "Windows"
            ],
            [
              "environment",
              "Test"
            ],
            [
              "exception-class",
              "System.NotImplementedException"
            ],
            [
              "level",
              "error"
            ],
            [
              "os",
              "Windows 10"
            ],
            [
              "os.name",
              "Windows"
            ],
            [
              "runtime",
              ".NET Framework 4.8.4645.0"
            ],
            [
              "runtime.name",
              ".NET Framework"
            ],
            [
              "release",
              "313864-test"
            ],
            [
              "user",
              "id:29723909"
            ],
            [
              "server-ip",
              "35.184.88.245"
            ],
            [
              "server_name",
              "TEST-WEB-5446"
            ],
            [
              "site-name",
              "test.buildertrend.net"
            ],
            [
              "transaction-id",
              "e6da8bde-4b2a-4bb3-8096-ed498137eedb"
            ],
            [
              "url",
              "https://test.buildertrend.net/api/Payments/"
            ]
          ],
          "culprit": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs in void OwnerInvoicesManager.SetLineItemUnitCost(LineItem invoiceLineItem, IMarkupLineItem markupLineItem, LineItemType lineIte...",
          "release": "313864-test",
          "_metrics": {
            "bytes.ingested.event": 27492,
            "bytes.stored.event": 45215
          },
          "web_url": "https://sentry.io/organizations/buildertrend/issues/4435706223/events/9984f6faec874f929c321635751046c3/",
          "metadata": {
            "in_app_frame_mix": "mixed",
            "display_title_with_tree_label": false,
            "function": "void OwnerInvoicesManager.SetLineItemUnitCost(LineItem invoiceLineItem, IMarkupLineItem markupLineItem, LineItemType lineItemType, bool? isCostPlus)",
            "type": "System.NotImplementedException",
            "value": "Unknown markup column",
            "filename": "C:\\adoBuild1\\_work\\2\\s\\BusinessLogic.Managers\\OwnerInvoicesManager.cs"
          },
          "level": "error",
          "datetime": "2023-08-29T20:54:22.510752Z",
          "dist": null,
          "project": 5790930,
          "modules": {
            "Google.Cloud.Kms.V1": "2.7.0.0",
            "Handlers.Accounting": "1.0.0.0",
            "System.Numerics": "4.0.0.0",
            "Grpc.Core": "2.0.0.0",
            "Serilog.Extensions.Logging": "2.0.0.0",
            "IP2Location": "4.0.0.0",
            "Microsoft.Extensions.FileProviders.Physical": "3.1.0.0",
            "Imazen.Common": "0.7.8.0",
            "Microsoft.Extensions.Configuration": "3.1.0.0",
            "Microsoft.Owin.Security.OpenIdConnect": "4.2.0.0",
            "App_Web_selectionfavoritedashboard.ascx.f9228c55": "0.0.0.0",
            "Microsoft.AspNetCore.Connections.Abstractions": "3.0.0.0",
            "Microsoft.IO.RecyclableMemoryStream": "1.2.2.0",
            "AutoMapper": "10.0.0.0",
            "HttpMultipartParser": "2.2.4.0",
            "System.ValueTuple": "4.0.3.0",
            "App_Web_logout.aspx.cdcab7d2": "0.0.0.0",
            "MoreLinq": "3.3.2.0",
            "Magick.NET-Q16-AnyCPU": "13.1.0.0",
            "App_Web_selectioncards.aspx.7643279e": "0.0.0.0",
            "System.Security.Cryptography.Primitives": "4.0.0.0",
            "Microsoft.Owin.Security": "4.2.0.0",
            "Serilog.Enrichers.Thread": "2.0.0.0",
            "System.Web.Optimization": "1.1.0.0",
            "Clients.WebApi": "1.0.0.0",
            "Intuit.Ipp.Data": "14.6.3.4",
            "Microsoft.Extensions.Logging.Configuration": "3.1.0.0",
            "Hangfire.Core": "1.7.33.0",
            "Google.Api.Gax": "3.6.0.0",
            "Excel": "2.1.2.3",
            "Intuit.Ipp.Diagnostics": "14.6.3.4",
            "App_Web_receiptlist.aspx.5055c936": "0.0.0.0",
            "System.IdentityModel": "4.0.0.0",
            "Microsoft.Owin.Security.Cookies": "4.2.0.0",
            "MongoDB.Driver": "2.19.1.0",
            "System.Net.Http.Formatting": "5.2.7.0",
            "Microsoft.Win32.Registry": "5.0.0.0",
            "nClam": "4.0.1.0",
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "3.1.0.0",
            "Microsoft.VisualBasic.Activities.Compiler": "10.0.0.0",
            "System.Diagnostics.PerformanceCounter": "5.0.0.0",
            "System.ServiceModel.Activities": "4.0.0.0",
            "System.Data.DataSetExtensions": "4.0.0.0",
            "App_Web_proposalestimates.ascx.7178b147": "0.0.0.0",
            "App_Web_selectionsmasterpage.master.7371103c": "0.0.0.0",
            "App_Web_btadminmaster.master.91644b2f": "0.0.0.0",
            "Dropbox.Api": "6.14.0.0",
            "Atalasoft.dotImage.PdfReader": "11.4.0.349",
            "Google.Cloud.PubSub.V1": "2.7.0.0",
            "System.Runtime.Serialization": "4.0.0.0",
            "NodaTime": "3.1.9.0",
            "Google.Cloud.DevTools.Common": "2.1.0.0",
            "Microsoft.IdentityModel.Protocols": "5.3.0.0",
            "Polly": "7.0.0.0",
            "Google.Apis.Core": "1.55.0.0",
            "App_Web_btimagebutton.ascx.2f5a3276": "0.0.0.0",
            "gma.Drawing.ImageInfo": "1.0.0.0",
            "Google.Apis.Storage.v1": "1.55.0.2526",
            "System.Runtime.DurableInstancing": "4.0.0.0",
            "Google.Cloud.Logging.Log4Net": "3.3.0.0",
            "App_Web_posimportdropdownmenu.ascx.b2d45495": "0.0.0.0",
            "SimpleObfuscator": "1.0.0.0",
            "Grpc.Net.Client": "2.0.0.0",
            "Microsoft.IdentityModel.Logging": "6.10.2.0",
            "Intuit.Ipp.Security": "14.6.3.4",
            "System.Interactive.Async": "5.1.0.0",
            "Microsoft.Bcl.AsyncInterfaces": "6.0.0.0",
            "App_Web_rootmaster.master.7371103c": "0.0.0.0",
            "System.Text.Encoding": "4.0.0.0",
            "App_Web_btdropdownlist.ascx.2f5a3276": "0.0.0.0",
            "Microsoft.Extensions.FileSystemGlobbing": "3.1.0.0",
            "Buildertrend.Utilities.Ocr.Veryfi": "1.0.0.0",
            "App_Web_adminmain.aspx.41cb4f82": "0.0.0.0",
            "System.Security": "4.0.0.0",
            "System.Net.Http": "4.0.0.0",
            "Microsoft.Owin": "4.2.0.0",
            "Google.Apis.PlatformServices": "1.55.0.0",
            "System.EnterpriseServices": "4.0.0.0",
            "Google.Protobuf": "3.19.3.0",
            "CaptchaImage": "1.0.2770.19138",
            "Handlers.Merchants": "1.0.0.0",
            "App_Web_masterpagebase.master.7371103c": "0.0.0.0",
            "Microsoft.Extensions.Logging": "3.1.0.0",
            "Microsoft.Build.Framework": "4.0.0.0",
            "Newtonsoft.Json": "13.0.0.0",
            "Serilog.Sinks.File": "2.0.0.0",
            "System.Diagnostics.DiagnosticSource": "5.0.0.0",
            "System.Configuration.ConfigurationManager": "4.0.2.0",
            "RedLockNet.SERedis": "2.2.0.0",
            "ICSharpCode.SharpZipLib": "1.4.2.13",
            "App_Web_btdropdownmenu.ascx.72c91787": "0.0.0.0",
            "HtmlSanitizer": "4.0.0.0",
            "System.Linq": "4.0.0.0",
            "Braintree": "5.15.0.0",
            "System.Security.Principal.Windows": "5.0.0.0",
            "System.Xml": "4.0.0.0",
            "Hangfire.Dashboard.Management.v2": "0.0.0.0",
            "Microsoft.IdentityModel.JsonWebTokens": "6.10.2.0",
            "System.Net.Http.Extensions": "2.2.29.0",
            "Xero.NetStandard.OAuth2Client": "1.6.0.0",
            "SerilogTraceListener": "0.0.0.0",
            "Clients.Atalasoft": "1.0.0.0",
            "App_Web_downloadplanswiftplugincontrol.ascx.8ef775db": "0.0.0.0",
            "System.Web.RegularExpressions": "4.0.0.0",
            "System.Web.Extensions": "4.0.0.0",
            "System.Data.SqlClient": "4.6.1.5",
            "Atalasoft.dotImage.PdfDoc.Bridge": "11.4.0.349",
            "WebGrease": "1.5.2.14234",
            "K4os.Hash.xxHash": "1.0.6.0",
            "System.Net.Requests": "4.0.0.0",
            "Google.Apis.Auth": "1.55.0.0",
            "System.Security.AccessControl": "6.0.0.0",
            "Serilog.Sinks.Console": "3.1.1.0",
            "Intuit.Ipp.ReportService": "14.6.3.4",
            "App_Web_adminautologin.aspx.41cb4f82": "0.0.0.0",
            "System.Text.Encoding.Extensions": "4.0.0.0",
            "System.Text.Encoding.CodePages": "7.0.0.0",
            "Microsoft.Extensions.Logging.Debug": "3.1.0.0",
            "App_Web_bttabcontrol.ascx.6bb32623": "0.0.0.0",
            "System.Net.Http.Json": "5.0.0.0",
            "App_Web_btadminnavigationenabledmaster.master.7ab75745": "0.0.0.0",
            "Microsoft.CodeDom.Providers.DotNetCompilerPlatform": "2.0.1.0",
            "System.WorkflowServices": "4.0.0.0",
            "DAL.Core": "1.0.0.0",
            "System.Security.Cryptography.Xml": "4.0.1.0",
            "MongoDB.Bson": "2.19.1.0",
            "StrongGrid": "0.50.2.0",
            "System.Threading.Tasks.Dataflow": "4.6.3.0",
            "Microsoft.Extensions.Logging.EventLog": "3.1.0.0",
            "Microsoft.Web.Infrastructure": "1.0.0.0",
            "System.Resources.ResourceManager": "4.0.0.0",
            "NPOI.OpenXml4Net": "2.5.1.0",
            "System.Web.Http.WebHost": "5.2.7.0",
            "DotNetZip": "1.16.0.0",
            "App_Web_btcheckbox.ascx.2f5a3276": "0.0.0.0",
            "K4os.Compression.LZ4.Streams": "1.2.16.0",
            "Buildertrend.Utilities.Ocr": "1.0.0.0",
            "Microsoft.AspNetCore.SignalR.Common": "3.0.0.0",
            "Microsoft.AspNet.Identity.Owin": "2.0.0.0",
            "Google.Cloud.Storage.V1": "3.6.0.0",
            "LightInject": "6.5.2.0",
            "Microsoft.AspNetCore.SignalR.Protocols.Json": "3.0.0.0",
            "System.Xml.Linq": "4.0.0.0",
            "System.Text.Encodings.Web": "6.0.0.0",
            "Microsoft.AspNetCore.Cryptography.KeyDerivation": "7.0.0.0",
            "Microsoft.AspNetCore.Http.Abstractions": "2.2.0.0",
            "jose-jwt": "4.1.0.0",
            "Microsoft.AspNetCore.Cryptography.Internal": "7.0.0.0",
            "RedLockNet.Abstractions": "2.2.0.0",
            "Owin": "1.0.0.0",
            "Atalasoft.dotImage.Ocr": "11.4.0.349",
            "Intuit.Ipp.OAuth2PlatformClient": "14.6.3.4",
            "System.Workflow.Runtime": "4.0.0.0",
            "Microsoft.Extensions.Hosting": "3.1.0.0",
            "System.Web.Cors": "5.2.7.0",
            "App_Web_btdropdownmenuitem.ascx.72c91787": "0.0.0.0",
            "AngleSharp": "0.9.9.0",
            "Microsoft.AspNetCore.Hosting.Server.Abstractions": "2.2.0.0",
            "App_Web_btlistpager.ascx.6bb32623": "0.0.0.0",
            "App_Web_inlineedit.ascx.6bb32623": "0.0.0.0",
            "Grpc.Auth": "2.0.0.0",
            "Clients.Hangfire.RecurringJobs": "1.0.0.0",
            "Google.Api.Gax.Grpc": "3.5.0.0",
            "App_Web_default.aspx.41cb4f82": "0.0.0.0",
            "Microsoft.Build.Utilities.v4.0": "4.0.0.0",
            "Buildertrend_WebLib": "1.0.8641.35186",
            "App_Web_summarygrid.aspx.cdcab7d2": "0.0.0.0",
            "NPOI.OpenXmlFormats": "2.5.1.0",
            "Microsoft.Extensions.Options": "3.1.7.0",
            "Microsoft.AspNetCore.Http.Features": "3.1.0.0",
            "Clients.WebApiLib": "1.0.0.0",
            "Microsoft.AspNetCore.Http.Connections.Client": "3.0.0.0",
            "Serilog.Enrichers.Environment": "2.0.0.0",
            "Microsoft.Extensions.ObjectPool": "2.2.0.0",
            "System.Windows.Forms": "4.0.0.0",
            "Trirand.Web": "4.5.4.0",
            "Sentry.DiagnosticSource": "3.25.0.0",
            "Auth0.Core": "7.20.0.0",
            "BusinessLogic.Engines": "1.0.0.0",
            "System.Xaml": "4.0.0.0",
            "System.Reflection.Metadata": "5.0.0.0",
            "Google.Cloud.Logging.Type": "3.3.0.0",
            "Atalasoft.dotImage.AdvancedDocClean": "11.4.0.349",
            "System.Threading.Tasks.Extensions": "4.2.0.1",
            "System.Web.Mobile": "4.0.0.0",
            "System.Buffers": "4.0.3.0",
            "App_Web_loginnotrequiredmaster.master.1880769f": "0.0.0.0",
            "App_Web_adminbuilders.aspx.41cb4f82": "0.0.0.0",
            "System.IO": "4.0.0.0",
            "System.Collections": "4.0.0.0",
            "Microsoft.Extensions.Logging.Abstractions": "3.1.0.0",
            "Global.DependencyInjection": "1.0.0.0",
            "KellermanSoftware.Compare-NET-Objects": "4.57.0.0",
            "Microsoft.Extensions.DependencyInjection": "3.1.22.0",
            "Microsoft.CSharp": "4.0.0.0",
            "App_Web_bttab.ascx.6bb32623": "0.0.0.0",
            "BTSerializeJSAttribute": "1.2.0.0",
            "Microsoft.Extensions.Options.ConfigurationExtensions": "3.1.0.0",
            "Global.SignalrModels": "1.0.0.0",
            "Microsoft.Extensions.Configuration.Xml": "2.2.0.0",
            "App_global.asax": "0.0.0.0",
            "Pathoschild.Http.Client": "3.2.0.0",
            "App_Web_btadminnavigationdisabledmaster.master.7ab75745": "0.0.0.0",
            "AWSSDK.SecurityToken": "3.3.0.0",
            "Microsoft.AspNet.Identity.Core": "2.0.0.0",
            "System.ServiceModel.Internals": "4.0.0.0",
            "Clients.Hangfire.OneTimeJobs": "1.0.0.0",
            "AdvancedIntellect.Ssl": "2.0.0.6",
            "aspNetIMAP": "1.8.0.0",
            "Microsoft.Extensions.Primitives": "3.1.7.0",
            "QbSync.QbXml": "0.0.3.0",
            "antlr.runtime": "2.7.6.2",
            "Serilog.Settings.Configuration": "3.1.0.0",
            "System.Drawing.Common": "7.0.0.0",
            "System.Web.Http": "5.2.7.0",
            "Microsoft.Azure.WebJobs.Host": "3.0.18.0",
            "Microsoft.Azure.WebJobs": "3.0.18.0",
            "Microsoft.Azure.Functions.Extensions": "1.1.0.0",
            "DAL": "1.0.0.0",
            "System.Security.Permissions": "7.0.0.0",
            "App_Web_proposalpreviewsection.ascx.924a9997": "0.0.0.0",
            "System.Web": "4.0.0.0",
            "GenericParsing": "1.1.3.17129",
            "RestSharp": "106.12.0.0",
            "Microsoft.IdentityModel.Tokens": "6.10.2.0",
            "System.Runtime.InteropServices.RuntimeInformation": "4.0.0.0",
            "StackExchange.Redis": "2.0.0.0",
            "BuilderTrend_Web": "1.0.8641.35345",
            "App_Web_ownerselectioncards.aspx.7643279e": "0.0.0.0",
            "BusinessLogic.Managers": "1.0.0.0",
            "System.Net.Primitives": "4.0.0.0",
            "TimeZoneConverter": "3.3.0.0",
            "Microsoft.Extensions.Logging.EventSource": "3.1.0.0",
            "App_Web_categorylocationview.ascx.f9228c55": "0.0.0.0",
            "Microsoft.Extensions.Configuration.FileExtensions": "3.1.0.0",
            "System.Web.Http.Cors": "5.2.7.0",
            "App_Web_btdropdownlistlegacy.ascx.2f5a3276": "0.0.0.0",
            "Intuit.Ipp.WebHooksService": "14.6.3.4",
            "System.Web.Services": "4.0.0.0",
            "Microsoft.Net.Http.Headers": "2.2.8.0",
            "Microsoft.AspNetCore.SignalR.Client": "3.0.0.0",
            "BouncyCastle.Crypto": "1.8.6.0",
            "System.Xaml.Hosting": "4.0.0.0",
            "System.Data.SqlXml": "4.0.0.0",
            "System.Security.Cryptography.Algorithms": "4.0.0.0",
            "Salesforce.Common": "1.0.0.0",
            "Microsoft.Diagnostics.Tracing.TraceEvent": "2.0.2.0",
            "Handlers.DataAccessHandlers": "1.0.0.0",
            "System.Runtime.Extensions": "4.0.0.0",
            "HtmlAgilityPack": "1.11.24.0",
            "Microsoft.Extensions.Configuration.UserSecrets": "3.1.0.0",
            "Serilog": "2.0.0.0",
            "Microsoft.AspNetCore.Http.Extensions": "2.2.0.0",
            "Google.Api.Gax.Grpc.GrpcCore": "3.5.0.0",
            "Clients.Hangfire.Common": "1.0.0.0",
            "App_Browsers": "0.0.0.0",
            "Datadog.Trace.ClrProfiler.Managed.Loader": "2.14.0.0",
            "System.Net.Http.WebRequest": "4.0.0.0",
            "App_Web_asyncjobpicker.ascx.6bb32623": "0.0.0.0",
            "System.Data": "4.0.0.0",
            "App_Web_bttextboxlegacy.ascx.2f5a3276": "0.0.0.0",
            "K4os.Compression.LZ4": "1.2.16.0",
            "Ical.Net": "1.0.0.0",
            "Imageflow.Net": "0.0.0.0",
            "Intuit.Ipp.OAuth2PlatformClient.Diagnostics": "14.6.3.4",
            "App_Web_lineitemmarkup.ascx.7178b147": "0.0.0.0",
            "Buildertrend.Utilities.Core": "1.0.5.0",
            "App_Web_proposalworksheet.ascx.924a9997": "0.0.0.0",
            "MimeTypesMap": "1.0.8.0",
            "Microsoft.Extensions.Configuration.Json": "3.1.0.0",
            "Microsoft.VisualBasic": "10.0.0.0",
            "Magick.NET.Core": "13.1.0.0",
            "App_Web_btentitymapping.ascx.6bb32623": "0.0.0.0",
            "Hangfire.AspNet": "0.2.0.0",
            "Microsoft.Owin.Security.Jwt": "4.2.0.0",
            "Swashbuckle.Core": "1.0.0.0",
            "App_Web_costcatalog.ascx.6bb32623": "0.0.0.0",
            "Elasticsearch.Net": "7.0.0.0",
            "Global.DependencyResolver": "1.0.0.0",
            "MetadataExtractor": "2.7.2.0",
            "Microsoft.DotNet.PlatformAbstractions": "2.0.4.0",
            "Microsoft.Extensions.DependencyInjection.Abstractions": "3.1.22.0",
            "App_Web_btdatebox.ascx.2f5a3276": "0.0.0.0",
            "App_Web_ownersummaryagenda.aspx.cdcab7d2": "0.0.0.0",
            "System.Activities": "4.0.0.0",
            "App_Web_masterpageowner.master.7371103c": "0.0.0.0",
            "System.Net.Http.Primitives": "4.2.29.0",
            "System.Threading.Tasks": "4.0.0.0",
            "Microsoft.Extensions.Hosting.Abstractions": "3.1.0.0",
            "LightInject.WebApi": "2.0.0.0",
            "RebateService.Shared.Contracts": "1.0.42.0",
            "Global.Utilities": "1.0.0.0",
            "App_Web_masterpagebuilder.master.7371103c": "0.0.0.0",
            "App_Web_btrichtexteditor.ascx.2f5a3276": "0.0.0.0",
            "System.IO.Pipelines": "7.0.0.0",
            "Atalasoft.dotImage": "11.4.0.349",
            "System.CodeDom": "7.0.0.0",
            "Microsoft.AspNetCore.Http.Connections.Common": "3.0.0.0",
            "NPOI.OOXML": "2.5.1.0",
            "App_Web_weatherwidget.ascx.6bb32623": "0.0.0.0",
            "Sentry.AspNet": "3.25.0.0",
            "System.Threading": "4.0.0.0",
            "Elastic.Apm.AspNetFullFramework": "1.16.1.0",
            "Persits.Email": "5.4.0.4478",
            "PuppeteerSharp": "10.1.2.0",
            "aspNetMime": "2.8.0.0",
            "Google.Api.Gax.Rest": "3.6.0.0",
            "Microsoft.AspNet.SignalR.Client": "2.4.3.0",
            "Atalasoft.dotImage.Raw": "11.4.0.349",
            "Microsoft.Web.RedisSessionStateProvider": "4.0.1.0",
            "CsvHelper": "15.0.0.0",
            "Grpc.Core.Api": "2.0.0.0",
            "Salesforce.Force": "1.0.0.0",
            "App_Web_proposalimport.ascx.924a9997": "0.0.0.0",
            "Elastic.Apm": "1.16.1.0",
            "Serilog.Sinks.Trace": "2.0.0.0",
            "DotNetOpenAuth": "3.4.7.11121",
            "System": "4.0.0.0",
            "System.Memory": "4.0.1.2",
            "App_Web_bttextbox.ascx.2f5a3276": "0.0.0.0",
            "Snappier": "1.0.0.0",
            "Microsoft.AspNetCore.WebUtilities": "2.2.0.0",
            "App_Web_menu.ascx.56baee3b": "0.0.0.0",
            "System.Runtime.InteropServices": "4.0.0.0",
            "Intuit.Ipp.Core": "14.6.3.4",
            "App_Web_btdropdownchecklistlegacy.ascx.2f5a3276": "0.0.0.0",
            "ChargeBee": "3.8.0.0",
            "System.IdentityModel.Tokens.Jwt": "6.10.2.0",
            "System.Text.Json": "5.0.0.2",
            "Google.Cloud.Iam.V1": "2.3.0.0",
            "IdentityModel": "5.1.0.0",
            "System.Runtime": "4.0.0.0",
            "Atalasoft.PdfDoc": "11.4.0.349",
            "Microsoft.Extensions.Configuration.CommandLine": "3.1.0.0",
            "System.Runtime.CompilerServices.Unsafe": "6.0.0.0",
            "Microsoft.Extensions.Configuration.Binder": "3.1.0.0",
            "BuilderTrend": "0.0.0.0",
            "App_Web_googlemap.ascx.c03d9170": "0.0.0.0",
            "Grpc.Net.Common": "2.0.0.0",
            "Handlebars": "1.9.5.0",
            "App_Web_proposalformatsection.ascx.924a9997": "0.0.0.0",
            "Intuit.Ipp.EntitlementService": "14.6.3.4",
            "Microsoft.AspNetCore.Hosting.Abstractions": "2.2.0.0",
            "System.Workflow.Activities": "4.0.0.0",
            "Microsoft.Extensions.WebEncoders": "2.2.0.0",
            "Handlers.IntegrationHandlers": "1.0.8641.35175",
            "App_Web_default.aspx.ae7ca9bd": "0.0.0.0",
            "Pipelines.Sockets.Unofficial": "1.0.0.0",
            "Antlr3.Runtime": "3.4.1.9004",
            "Google.Apis.Auth.PlatformServices": "1.55.0.0",
            "Microsoft.Extensions.DependencyModel": "2.0.4.0",
            "LumenWorks.Framework.IO": "3.8.0.0",
            "System.ComponentModel.DataAnnotations": "4.0.0.0",
            "App_Web_proposalsbuildermasterpage.master.7371103c": "0.0.0.0",
            "App_Web_paymentslistcontrol.ascx.f02c758b": "0.0.0.0",
            "App_Web_worksheet.aspx.b672eb6f": "0.0.0.0",
            "Microsoft.Extensions.Http": "2.2.0.0",
            "Hangfire.Pro.Redis": "2.8.20.0",
            "netstandard": "2.0.0.0",
            "Ude.NetStandard": "1.0.2.0",
            "App_Web_ownercategorylocations.aspx.7643279e": "0.0.0.0",
            "System.Core": "4.0.0.0",
            "Auth0.ManagementApi": "7.20.0.0",
            "Intuit.Ipp.DataService": "14.6.3.4",
            "Atalasoft.Shared": "11.4.0.349",
            "Google.Apis": "1.55.0.0",
            "Global.Core": "1.0.0.0",
            "Datadog.Trace": "2.14.0.0",
            "VimeoDotNet": "2.0.0.23",
            "System.Dynamic": "4.0.0.0",
            "Microsoft.AspNetCore.Http": "2.2.2.0",
            "System.Diagnostics.EventLog": "7.0.0.0",
            "System.Drawing": "4.0.0.0",
            "App_Web_ownerselectionsmasterpage.master.7371103c": "0.0.0.0",
            "App_Web_bt_contextmenu.ascx.6bb32623": "0.0.0.0",
            "System.Linq.Async": "5.1.0.0",
            "mscorlib": "4.0.0.0",
            "System.Data.Linq": "4.0.0.0",
            "Intuit.Ipp.Retry": "14.6.3.4",
            "System.ServiceModel.Web": "4.0.0.0",
            "App_Web_btaddress.ascx.6bb32623": "0.0.0.0",
            "App_Web_externalnonembeddablemaster.master.af2f93c0": "0.0.0.0",
            "Atalasoft.dotImage.WebControls": "11.4.0.349",
            "Avalara.AvaTax.RestClient.net45": "20.9.0.0",
            "DnsClient": "1.6.1.0",
            "System.ComponentModel.Annotations": "4.2.1.0",
            "Microsoft.Owin.Host.SystemWeb": "4.2.0.0",
            "App_Web_tooltip.ascx.6bb32623": "0.0.0.0",
            "System.ServiceModel.Activation": "4.0.0.0",
            "App_Web_default.aspx.cdcab7d2": "0.0.0.0",
            "Google.Cloud.Logging.V2": "3.4.0.0",
            "XmpCore": "6.1.10.1",
            "Microsoft.AspNetCore.StaticFiles": "2.2.0.0",
            "Microsoft.AspNetCore.SignalR.Client.Core": "3.0.0.0",
            "App_Web_fileuploadonnewentity.ascx.6bb32623": "0.0.0.0",
            "App_Web_worksheetlineitems.ascx.924a9997": "0.0.0.0",
            "System.Design": "4.0.0.0",
            "App_Web_proposalpreview.ascx.924a9997": "0.0.0.0",
            "Microsoft.IdentityModel.Protocols.OpenIdConnect": "5.3.0.0",
            "MongoDB.Libmongocrypt": "1.7.0.0",
            "OSExtensions": "1.0.0.0",
            "System.Configuration": "4.0.0.0",
            "Microsoft.Extensions.Logging.Console": "3.1.0.0",
            "Hangfire.Heartbeat": "1.0.0.0",
            "Intuit.Ipp.GlobalTaxService": "14.6.3.4",
            "Twilio": "5.65.2.0",
            "System.Workflow.ComponentModel": "4.0.0.0",
            "Google.Api.CommonProtos": "2.5.0.0",
            "System.Runtime.Caching": "4.0.0.0",
            "log4net": "2.0.15.0",
            "ZstdSharp": "0.6.2.0",
            "IppDotNetSdkForQuickBooksApiV3": "14.6.3.4",
            "System.ServiceModel": "4.0.0.0",
            "App_Web_leadproposals.aspx.b4a5e1e8": "0.0.0.0",
            "MongoDB.Driver.Core": "2.19.1.0",
            "Serilog.Sinks.Debug": "2.0.0.0",
            "Nest": "7.0.0.0",
            "Microsoft.Extensions.Logging.Log4Net.AspNetCore": "2.2.12.0",
            "Microsoft.VisualStudio.TestPlatform.TestFramework": "14.0.0.0",
            "App_Web_btprintheader.ascx.6bb32623": "0.0.0.0",
            "Microsoft.JScript": "10.0.0.0",
            "System.Collections.Immutable": "7.0.0.0",
            "Microsoft.AspNet.SessionState.SessionStateModule": "1.1.0.0",
            "Intuit.Ipp.QueryFilter": "14.6.3.4",
            "JsonSubTypes": "1.5.2.0",
            "UnitsNet": "4.0.0.0",
            "App_Web_proposalheader.ascx.924a9997": "0.0.0.0",
            "Intuit.Ipp.Utility": "14.6.3.4",
            "JWT": "4.0.0.0",
            "Atalasoft.dotImage.Pdf": "11.4.0.349",
            "SMDiagnostics": "4.0.0.0",
            "System.Numerics.Vectors": "4.1.4.0",
            "System.Threading.Channels": "5.0.0.0",
            "App_Web_proposalformat.ascx.924a9997": "0.0.0.0",
            "Sentry": "3.25.0.0",
            "App_Web_proposalpaymentstatus.ascx.924a9997": "0.0.0.0",
            "System.Web.DynamicData": "4.0.0.0",
            "Atalasoft.dotImage.Lib": "11.4.0.349",
            "Microsoft.Diagnostics.FastSerialization": "1.0.0.0",
            "System.Web.ApplicationServices": "4.0.0.0",
            "Xero.NetStandard.OAuth2": "0.0.0.0",
            "FirebaseAdmin": "1.9.1.0",
            "Nager.Country": "3.1.1.0",
            "AWSSDK.Core": "3.3.0.0",
            "WebClientShared": "1.0.0.0",
            "Intuit.Ipp.Exception": "14.6.3.4",
            "BT_Encryptor": "1.0.0.0",
            "RestSharp.Serializers.NewtonsoftJson": "106.11.7.0",
            "System.Transactions": "4.0.0.0",
            "Microsoft.Extensions.FileProviders.Abstractions": "3.1.0.0",
            "NPOI": "2.5.1.0",
            "Microsoft.Extensions.Configuration.Abstractions": "3.1.0.0",
            "Microsoft.Owin.Security.OAuth": "4.2.0.0",
            "SharpCompress": "0.30.1.0",
            "App_Web_owneralertsbar.ascx.6bb32623": "0.0.0.0",
            "Hangfire.Console": "1.4.2.0"
          },
          "hashes": [
            "83326b85625a049935378223fdb8f7f2",
            "2a8908aa0cc72c4d92b76f7cd05b4b3f"
          ]
        },
        "triggered_rule": ".NET Test Issues Teams Integration"
      },
      "actor": {
        "type": "application",
        "id": "sentry",
        "name": "Sentry"
      },
      "action": "triggered",
      "installation": {
        "uuid": "dbb4da9c-e292-48a8-9c4c-07f3f0bcce03"
      }
    },
    "resource": {
      "type": "cloud_run_revision",
      "labels": {
        "service_name": "sentry-test3",
        "project_id": "clear-network-397314",
        "configuration_name": "sentry-test3",
        "revision_name": "sentry-test3-00023-wif",
        "location": "us-central1"
      }
    },
    "timestamp": "2023-08-29T20:54:38.496202Z",
    "labels": {
      "instanceId": "00e676007309315d5dc71a5594d651af4bfaa432c85de9ef632f3630187acdd0a6b204a62f3a167a58e593aa76838c853747f3a4962e0ae0a3cf54fd55b5f5204103",
      "goog-managed-by": "cloudfunctions"
    },
    "logName": "projects/clear-network-397314/logs/run.googleapis.com%2Fstdout",
    "receiveTimestamp": "2023-08-29T20:54:38.833274443Z"
  }