const faker = {
    "insertId": "64ed40140003f729ffd7e87e",
    "jsonPayload": {
      "installation": {
        "uuid": "dbb4da9c-e292-48a8-9c4c-07f3f0bcce03"
      },
      "action": "triggered",
      "data": {
        "triggered_rule": ".NET Test Issues Teams Integration",
        "event": {
          "environment": "Test",
          "issue_url": "https://sentry.io/api/0/issues/4432298658/",
          "logger": "",
          "exception": {
            "values": [
              { 
                "raw_stacktrace": {
                  "frames": [
                    {
                      "context_line": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "module": null,
                      "snapshot": null,
                      "colno": null,
                      "lineno": null,
                      "post_context": null,
                      "platform": null,
                      "image_addr": null,
                      "pre_context": null,
                      "errors": null,
                      "trust": null,
                      "addr_mode": null,
                      "data": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "symbol": null,
                      "abs_path": null,
                      "symbol_addr": null,
                      "raw_function": null,
                      "in_app": false,
                      "instruction_addr": "0x87",
                      "vars": null,
                      "lock": null,
                      "filename": null
                    },
                    {
                      "post_context": null,
                      "vars": null,
                      "errors": null,
                      "lock": null,
                      "context_line": null,
                      "symbol": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "raw_function": null,
                      "snapshot": null,
                      "instruction_addr": "0xf3",
                      "filename": null,
                      "lineno": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "abs_path": null,
                      "image_addr": null,
                      "colno": null,
                      "pre_context": null,
                      "module": null,
                      "addr_mode": null,
                      "in_app": false,
                      "platform": null,
                      "trust": null,
                      "symbol_addr": null
                    },
                    {
                      "filename": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "symbol_addr": null,
                      "platform": null,
                      "pre_context": null,
                      "in_app": false,
                      "raw_function": null,
                      "module": null,
                      "lineno": null,
                      "post_context": null,
                      "instruction_addr": "0x1a4",
                      "snapshot": null,
                      "addr_mode": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "abs_path": null,
                      "colno": null,
                      "symbol": null,
                      "lock": null,
                      "data": null,
                      "image_addr": null,
                      "trust": null,
                      "errors": null,
                      "vars": null,
                      "context_line": null
                    },
                    {
                      "symbol_addr": null,
                      "addr_mode": null,
                      "lock": null,
                      "post_context": null,
                      "in_app": false,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "lineno": null,
                      "data": null,
                      "filename": null,
                      "abs_path": null,
                      "symbol": null,
                      "errors": null,
                      "vars": null,
                      "raw_function": null,
                      "snapshot": null,
                      "context_line": null,
                      "pre_context": null,
                      "image_addr": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "instruction_addr": "0x103",
                      "trust": null,
                      "module": null,
                      "platform": null,
                      "colno": null
                    },
                    {
                      "platform": null,
                      "lock": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "lineno": null,
                      "vars": null,
                      "addr_mode": null,
                      "filename": null,
                      "colno": null,
                      "symbol_addr": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "in_app": false,
                      "context_line": null,
                      "data": null,
                      "trust": null,
                      "image_addr": null,
                      "instruction_addr": "0x91",
                      "raw_function": null,
                      "pre_context": null,
                      "abs_path": null,
                      "snapshot": null,
                      "symbol": null,
                      "post_context": null,
                      "errors": null,
                      "module": null
                    },
                    {
                      "data": null,
                      "vars": null,
                      "filename": null,
                      "pre_context": null,
                      "module": null,
                      "instruction_addr": "0x103",
                      "symbol_addr": null,
                      "context_line": null,
                      "symbol": null,
                      "in_app": false,
                      "raw_function": null,
                      "lineno": null,
                      "addr_mode": null,
                      "snapshot": null,
                      "image_addr": null,
                      "platform": null,
                      "abs_path": null,
                      "lock": null,
                      "trust": null,
                      "post_context": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "errors": null,
                      "colno": null
                    },
                    {
                      "addr_mode": null,
                      "instruction_addr": "0x91",
                      "lineno": null,
                      "abs_path": null,
                      "lock": null,
                      "filename": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "pre_context": null,
                      "data": null,
                      "trust": null,
                      "context_line": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "snapshot": null,
                      "in_app": false,
                      "errors": null,
                      "colno": null,
                      "raw_function": null,
                      "post_context": null,
                      "symbol_addr": null,
                      "module": null,
                      "symbol": null,
                      "vars": null,
                      "platform": null,
                      "image_addr": null
                    },
                    {
                      "symbol_addr": null,
                      "addr_mode": null,
                      "post_context": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "filename": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "lineno": null,
                      "image_addr": null,
                      "raw_function": null,
                      "instruction_addr": "0x103",
                      "snapshot": null,
                      "pre_context": null,
                      "lock": null,
                      "trust": null,
                      "symbol": null,
                      "vars": null,
                      "in_app": false,
                      "context_line": null,
                      "errors": null,
                      "colno": null,
                      "module": null,
                      "platform": null,
                      "abs_path": null
                    },
                    {
                      "symbol": null,
                      "lock": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "data": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "filename": null,
                      "context_line": null,
                      "colno": null,
                      "instruction_addr": "0x91",
                      "raw_function": null,
                      "symbol_addr": null,
                      "vars": null,
                      "errors": null,
                      "pre_context": null,
                      "trust": null,
                      "lineno": null,
                      "abs_path": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "image_addr": null,
                      "module": null,
                      "platform": null,
                      "post_context": null,
                      "in_app": false
                    },
                    {
                      "in_app": false,
                      "image_addr": null,
                      "data": null,
                      "post_context": null,
                      "instruction_addr": "0xab",
                      "abs_path": null,
                      "pre_context": null,
                      "errors": null,
                      "lineno": null,
                      "context_line": null,
                      "platform": null,
                      "raw_function": null,
                      "module": null,
                      "colno": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "vars": null,
                      "filename": null,
                      "trust": null,
                      "addr_mode": null,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "symbol": null,
                      "snapshot": null,
                      "symbol_addr": null,
                      "lock": null
                    },
                    {
                      "abs_path": null,
                      "colno": null,
                      "lock": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "module": null,
                      "trust": null,
                      "in_app": false,
                      "vars": null,
                      "instruction_addr": "0x0",
                      "context_line": null,
                      "addr_mode": null,
                      "platform": null,
                      "filename": null,
                      "raw_function": null,
                      "symbol": null,
                      "symbol_addr": null,
                      "data": null,
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "errors": null,
                      "pre_context": null,
                      "lineno": null,
                      "post_context": null,
                      "image_addr": null,
                      "snapshot": null
                    },
                    {
                      "filename": "Controllers\\OnlinePaymentsOnboardingController.put.cs",
                      "addr_mode": null,
                      "symbol_addr": null,
                      "lock": null,
                      "data": null,
                      "abs_path": "Controllers\\OnlinePaymentsOnboardingController.put.cs",
                      "symbol": null,
                      "raw_function": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "errors": null,
                      "instruction_addr": "0x7f",
                      "pre_context": null,
                      "function": "async Task<BT_ServiceResponse<UpdateCustomOnboardingResponse>> OnlinePaymentsOnboardingController.CreateVerificationAsync(UpdateCustomOnboardingRequest request)",
                      "module": null,
                      "platform": null,
                      "context_line": null,
                      "post_context": null,
                      "in_app": true,
                      "snapshot": null,
                      "vars": null,
                      "lineno": 26,
                      "colno": 13,
                      "image_addr": null,
                      "trust": null
                    },
                    {
                      "errors": null,
                      "vars": null,
                      "snapshot": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "context_line": null,
                      "symbol": null,
                      "in_app": true,
                      "trust": null,
                      "symbol_addr": null,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "data": null,
                      "lock": null,
                      "function": "async Task<UpdateCustomOnboardingResponse> OnlinePaymentsOnboardingManager.CreateVerificationAsync(UpdateCustomOnboardingRequest clientRequest, IBTBuilders builder)",
                      "colno": 13,
                      "image_addr": null,
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "addr_mode": null,
                      "platform": null,
                      "lineno": 576,
                      "pre_context": null,
                      "post_context": null,
                      "raw_function": null,
                      "instruction_addr": "0x111",
                      "module": null
                    },
                    {
                      "instruction_addr": "0x14",
                      "abs_path": null,
                      "snapshot": null,
                      "module": null,
                      "symbol": null,
                      "pre_context": null,
                      "lineno": null,
                      "lock": null,
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "raw_function": null,
                      "post_context": null,
                      "in_app": false,
                      "errors": null,
                      "context_line": null,
                      "data": null,
                      "vars": null,
                      "image_addr": null,
                      "trust": null,
                      "function": "TSource[] Enumerable.ToArray<TSource>(IEnumerable<TSource> source)",
                      "addr_mode": null,
                      "symbol_addr": null,
                      "platform": null,
                      "colno": null,
                      "filename": null
                    },
                    {
                      "lock": null,
                      "raw_function": null,
                      "lineno": null,
                      "addr_mode": null,
                      "vars": null,
                      "errors": null,
                      "platform": null,
                      "symbol_addr": null,
                      "filename": null,
                      "context_line": null,
                      "snapshot": null,
                      "data": null,
                      "post_context": null,
                      "abs_path": null,
                      "in_app": false,
                      "trust": null,
                      "module": null,
                      "symbol": null,
                      "colno": null,
                      "image_addr": null,
                      "pre_context": null,
                      "function": "new Buffer<TElement>(IEnumerable<TElement> source)",
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "instruction_addr": "0x72"
                    },
                    {
                      "symbol": null,
                      "function": "bool WhereSelectArrayIterator<TSource, TResult>.MoveNext()",
                      "vars": null,
                      "trust": null,
                      "colno": null,
                      "data": null,
                      "abs_path": null,
                      "errors": null,
                      "context_line": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "raw_function": null,
                      "lock": null,
                      "platform": null,
                      "addr_mode": null,
                      "instruction_addr": "0x41",
                      "in_app": false,
                      "post_context": null,
                      "filename": null,
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "image_addr": null,
                      "module": null,
                      "lineno": null
                    },
                    {
                      "colno": 69,
                      "module": null,
                      "function": "Task<UpdateCustomOnboardingResponse> OnlinePaymentsOnboardingManager.CreateVerificationAsync(UpdateCustomOnboardingRequest clientRequest, IBTBuilders builder)+(UpdateCustomOnboardingRequestIndividual i) => { }",
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "snapshot": null,
                      "platform": null,
                      "raw_function": null,
                      "data": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "in_app": true,
                      "post_context": null,
                      "symbol_addr": null,
                      "vars": null,
                      "instruction_addr": "0x0",
                      "lineno": 585,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "trust": null,
                      "image_addr": null,
                      "lock": null,
                      "context_line": null,
                      "symbol": null,
                      "pre_context": null,
                      "addr_mode": null,
                      "errors": null
                    },
                    {
                      "snapshot": null,
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "symbol": null,
                      "context_line": null,
                      "instruction_addr": "0x61",
                      "function": "CustomerOnboardingServiceSnapshotIndividual OnlinePaymentsOnboardingManager.GetSnapshotIndividualFromRequest(UpdateCustomOnboardingRequestIndividual individual)",
                      "data": null,
                      "post_context": null,
                      "image_addr": null,
                      "colno": 13,
                      "addr_mode": null,
                      "in_app": true,
                      "vars": null,
                      "lineno": 1124,
                      "symbol_addr": null,
                      "trust": null,
                      "raw_function": null,
                      "pre_context": null,
                      "lock": null,
                      "platform": null,
                      "module": null,
                      "errors": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs"
                    },
                    {
                      "vars": null,
                      "in_app": false,
                      "filename": null,
                      "addr_mode": null,
                      "module": null,
                      "data": null,
                      "trust": null,
                      "errors": null,
                      "instruction_addr": "0xf",
                      "pre_context": null,
                      "symbol_addr": null,
                      "platform": null,
                      "package": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "lineno": null,
                      "snapshot": null,
                      "lock": null,
                      "abs_path": null,
                      "image_addr": null,
                      "function": "T Nullable<T>.get_Value()",
                      "colno": null,
                      "raw_function": null,
                      "post_context": null,
                      "context_line": null,
                      "symbol": null
                    }
                  ]
                },
                "thread_id": 122,
                "value": "Nullable object must have a value.",
                "type": "System.InvalidOperationException",
                "stacktrace": {
                  "frames": [
                    {
                      "post_context": null,
                      "image_addr": null,
                      "trust": null,
                      "lineno": null,
                      "addr_mode": null,
                      "raw_function": null,
                      "symbol": null,
                      "filename": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "snapshot": null,
                      "platform": null,
                      "instruction_addr": "0x87",
                      "lock": null,
                      "module": null,
                      "symbol_addr": null,
                      "colno": null,
                      "pre_context": null,
                      "vars": null,
                      "context_line": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "abs_path": null,
                      "function": "async Task<HttpResponseMessage> ExceptionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "errors": null
                    },
                    {
                      "instruction_addr": "0xf3",
                      "errors": null,
                      "abs_path": null,
                      "trust": null,
                      "image_addr": null,
                      "module": null,
                      "context_line": null,
                      "colno": null,
                      "pre_context": null,
                      "raw_function": null,
                      "lock": null,
                      "vars": null,
                      "filename": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "addr_mode": null,
                      "lineno": null,
                      "snapshot": null,
                      "function": "async Task<HttpResponseMessage> AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "post_context": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "platform": null,
                      "symbol_addr": null,
                      "in_app": false,
                      "symbol": null
                    },
                    {
                      "module": null,
                      "colno": null,
                      "lineno": null,
                      "pre_context": null,
                      "trust": null,
                      "errors": null,
                      "context_line": null,
                      "abs_path": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "vars": null,
                      "instruction_addr": "0x1a4",
                      "post_context": null,
                      "snapshot": null,
                      "platform": null,
                      "symbol": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterResult.ExecuteAsync(CancellationToken cancellationToken)",
                      "lock": null,
                      "image_addr": null,
                      "symbol_addr": null,
                      "filename": null,
                      "in_app": false,
                      "raw_function": null,
                      "addr_mode": null
                    },
                    {
                      "lock": null,
                      "post_context": null,
                      "lineno": null,
                      "colno": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "image_addr": null,
                      "errors": null,
                      "context_line": null,
                      "trust": null,
                      "snapshot": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "module": null,
                      "symbol_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "filename": null,
                      "symbol": null,
                      "pre_context": null,
                      "platform": null,
                      "instruction_addr": "0x103",
                      "abs_path": null,
                      "vars": null,
                      "addr_mode": null,
                      "raw_function": null
                    },
                    {
                      "lock": null,
                      "instruction_addr": "0x91",
                      "filename": null,
                      "addr_mode": null,
                      "symbol": null,
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "colno": null,
                      "raw_function": null,
                      "errors": null,
                      "lineno": null,
                      "trust": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "module": null,
                      "vars": null,
                      "pre_context": null,
                      "image_addr": null,
                      "symbol_addr": null,
                      "context_line": null,
                      "abs_path": null,
                      "snapshot": null,
                      "post_context": null,
                      "platform": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      }
                    },
                    {
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "raw_function": null,
                      "in_app": false,
                      "vars": null,
                      "errors": null,
                      "context_line": null,
                      "snapshot": null,
                      "image_addr": null,
                      "colno": null,
                      "symbol_addr": null,
                      "module": null,
                      "trust": null,
                      "lock": null,
                      "post_context": null,
                      "symbol": null,
                      "abs_path": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "lineno": null,
                      "pre_context": null,
                      "platform": null,
                      "filename": null,
                      "addr_mode": null,
                      "instruction_addr": "0x103"
                    },
                    {
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "addr_mode": null,
                      "raw_function": null,
                      "filename": null,
                      "trust": null,
                      "in_app": false,
                      "symbol_addr": null,
                      "vars": null,
                      "context_line": null,
                      "pre_context": null,
                      "image_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "abs_path": null,
                      "snapshot": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "platform": null,
                      "module": null,
                      "symbol": null,
                      "colno": null,
                      "lineno": null,
                      "errors": null,
                      "instruction_addr": "0x91",
                      "lock": null,
                      "post_context": null
                    },
                    {
                      "symbol_addr": null,
                      "pre_context": null,
                      "post_context": null,
                      "lock": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.ExecuteActionFilterAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation)",
                      "image_addr": null,
                      "filename": null,
                      "raw_function": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "lineno": null,
                      "platform": null,
                      "errors": null,
                      "symbol": null,
                      "addr_mode": null,
                      "in_app": false,
                      "abs_path": null,
                      "module": null,
                      "snapshot": null,
                      "trust": null,
                      "colno": null,
                      "instruction_addr": "0x103",
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "context_line": null,
                      "vars": null
                    },
                    {
                      "image_addr": null,
                      "instruction_addr": "0x91",
                      "symbol": null,
                      "colno": null,
                      "vars": null,
                      "function": "async Task<HttpResponseMessage> ActionFilterAttribute.CallOnActionExecutedAsync(HttpActionContext actionContext, CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) x 2",
                      "abs_path": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "in_app": false,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "post_context": null,
                      "raw_function": null,
                      "context_line": null,
                      "filename": null,
                      "addr_mode": null,
                      "errors": null,
                      "platform": null,
                      "lineno": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "lock": null,
                      "module": null,
                      "trust": null,
                      "pre_context": null
                    },
                    {
                      "image_addr": null,
                      "in_app": false,
                      "function": "async Task<HttpResponseMessage> ApiControllerActionInvoker.InvokeActionAsyncCore(HttpActionContext actionContext, CancellationToken cancellationToken)",
                      "context_line": null,
                      "raw_function": null,
                      "platform": null,
                      "module": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "symbol_addr": null,
                      "lineno": null,
                      "instruction_addr": "0xab",
                      "colno": null,
                      "symbol": null,
                      "abs_path": null,
                      "vars": null,
                      "post_context": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "errors": null,
                      "lock": null,
                      "snapshot": null,
                      "trust": null,
                      "pre_context": null,
                      "filename": null,
                      "addr_mode": null
                    },
                    {
                      "module": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "symbol": null,
                      "image_addr": null,
                      "lock": null,
                      "raw_function": null,
                      "platform": null,
                      "abs_path": null,
                      "package": "System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
                      "post_context": null,
                      "in_app": false,
                      "errors": null,
                      "addr_mode": null,
                      "snapshot": null,
                      "pre_context": null,
                      "lineno": null,
                      "function": "async Task<object> TaskHelpersExtensions.CastToObject<T>(Task<T> task)",
                      "context_line": null,
                      "instruction_addr": "0x0",
                      "filename": null,
                      "trust": null,
                      "symbol_addr": null,
                      "colno": null,
                      "vars": null
                    },
                    {
                      "symbol_addr": null,
                      "package": "Clients.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "context_line": null,
                      "vars": null,
                      "trust": null,
                      "colno": 13,
                      "lineno": 26,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "errors": null,
                      "symbol": null,
                      "module": null,
                      "image_addr": null,
                      "pre_context": null,
                      "lock": null,
                      "abs_path": "Controllers\\OnlinePaymentsOnboardingController.put.cs",
                      "raw_function": null,
                      "filename": "Controllers\\OnlinePaymentsOnboardingController.put.cs",
                      "snapshot": null,
                      "function": "async Task<BT_ServiceResponse<UpdateCustomOnboardingResponse>> OnlinePaymentsOnboardingController.CreateVerificationAsync(UpdateCustomOnboardingRequest request)",
                      "instruction_addr": "0x7f",
                      "post_context": null,
                      "addr_mode": null,
                      "platform": null,
                      "in_app": true
                    },
                    {
                      "post_context": null,
                      "symbol_addr": null,
                      "trust": null,
                      "snapshot": null,
                      "lineno": 576,
                      "instruction_addr": "0x111",
                      "vars": null,
                      "symbol": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "function": "async Task<UpdateCustomOnboardingResponse> OnlinePaymentsOnboardingManager.CreateVerificationAsync(UpdateCustomOnboardingRequest clientRequest, IBTBuilders builder)",
                      "addr_mode": null,
                      "colno": 13,
                      "image_addr": null,
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "lock": null,
                      "pre_context": null,
                      "in_app": true,
                      "module": null,
                      "raw_function": null,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "context_line": null,
                      "platform": null,
                      "errors": null
                    },
                    {
                      "module": null,
                      "pre_context": null,
                      "addr_mode": null,
                      "function": "TSource[] Enumerable.ToArray<TSource>(IEnumerable<TSource> source)",
                      "context_line": null,
                      "colno": null,
                      "image_addr": null,
                      "abs_path": null,
                      "raw_function": null,
                      "errors": null,
                      "lock": null,
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "symbol_addr": null,
                      "lineno": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "platform": null,
                      "trust": null,
                      "filename": null,
                      "vars": null,
                      "post_context": null,
                      "in_app": false,
                      "instruction_addr": "0x14",
                      "snapshot": null,
                      "symbol": null
                    },
                    {
                      "in_app": false,
                      "vars": null,
                      "trust": null,
                      "errors": null,
                      "instruction_addr": "0x72",
                      "symbol_addr": null,
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "post_context": null,
                      "context_line": null,
                      "module": null,
                      "pre_context": null,
                      "lock": null,
                      "lineno": null,
                      "raw_function": null,
                      "filename": null,
                      "colno": null,
                      "addr_mode": null,
                      "image_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "symbol": null,
                      "platform": null,
                      "snapshot": null,
                      "function": "new Buffer<TElement>(IEnumerable<TElement> source)",
                      "abs_path": null
                    },
                    {
                      "symbol": null,
                      "vars": null,
                      "trust": null,
                      "lock": null,
                      "pre_context": null,
                      "symbol_addr": null,
                      "module": null,
                      "platform": null,
                      "instruction_addr": "0x41",
                      "lineno": null,
                      "raw_function": null,
                      "post_context": null,
                      "image_addr": null,
                      "function": "bool WhereSelectArrayIterator<TSource, TResult>.MoveNext()",
                      "abs_path": null,
                      "errors": null,
                      "context_line": null,
                      "filename": null,
                      "colno": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "package": "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "snapshot": null,
                      "in_app": false,
                      "addr_mode": null
                    },
                    {
                      "vars": null,
                      "trust": null,
                      "instruction_addr": "0x0",
                      "lineno": 585,
                      "post_context": null,
                      "symbol_addr": null,
                      "snapshot": null,
                      "lock": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "symbol": null,
                      "context_line": null,
                      "addr_mode": null,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "in_app": true,
                      "errors": null,
                      "platform": null,
                      "image_addr": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "pre_context": null,
                      "raw_function": null,
                      "colno": 69,
                      "function": "Task<UpdateCustomOnboardingResponse> OnlinePaymentsOnboardingManager.CreateVerificationAsync(UpdateCustomOnboardingRequest clientRequest, IBTBuilders builder)+(UpdateCustomOnboardingRequestIndividual i) => { }",
                      "module": null
                    },
                    {
                      "symbol": null,
                      "post_context": null,
                      "image_addr": null,
                      "errors": null,
                      "lock": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      },
                      "addr_mode": null,
                      "abs_path": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "lineno": 1124,
                      "function": "CustomerOnboardingServiceSnapshotIndividual OnlinePaymentsOnboardingManager.GetSnapshotIndividualFromRequest(UpdateCustomOnboardingRequestIndividual individual)",
                      "symbol_addr": null,
                      "package": "BusinessLogic.Managers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                      "vars": null,
                      "context_line": null,
                      "raw_function": null,
                      "platform": null,
                      "trust": null,
                      "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
                      "pre_context": null,
                      "colno": 13,
                      "in_app": true,
                      "snapshot": null,
                      "instruction_addr": "0x61",
                      "module": null
                    },
                    {
                      "post_context": null,
                      "in_app": false,
                      "platform": null,
                      "lineno": null,
                      "colno": null,
                      "errors": null,
                      "raw_function": null,
                      "instruction_addr": "0xf",
                      "lock": null,
                      "image_addr": null,
                      "snapshot": null,
                      "addr_mode": null,
                      "package": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                      "trust": null,
                      "pre_context": null,
                      "vars": null,
                      "filename": null,
                      "abs_path": null,
                      "symbol_addr": null,
                      "function": "T Nullable<T>.get_Value()",
                      "module": null,
                      "context_line": null,
                      "symbol": null,
                      "data": {
                        "symbolicator_status": "unknown_image"
                      }
                    }
                  ]
                },
                "module": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
              }
            ]
          },
          "datetime": "2023-08-29T00:47:03.193431Z",
          "version": "7",
          "tags": [
            [
              "BT-Employee",
              "Tommy Hyre"
            ],
            [
              "app-type",
              "WebApp"
            ],
            [
              "browser",
              "Google Chrome 116"
            ],
            [
              "browser.name",
              "Google Chrome"
            ],
            [
              "builder-id",
              "98068"
            ],
            [
              "builder-name",
              "Hyre Builders Build Buildings"
            ],
            [
              "client_os.name",
              "Windows"
            ],
            [
              "environment",
              "Test"
            ],
            [
              "exception-class",
              "System.InvalidOperationException"
            ],
            [
              "level",
              "error"
            ],
            [
              "os",
              "Windows 10"
            ],
            [
              "os.name",
              "Windows"
            ],
            [
              "runtime",
              ".NET Framework 4.8.4645.0"
            ],
            [
              "runtime.name",
              ".NET Framework"
            ],
            [
              "release",
              "313498-test"
            ],
            [
              "user",
              "id:686792"
            ],
            [
              "server-ip",
              "35.184.88.245"
            ],
            [
              "server_name",
              "TEST-WEB-C080"
            ],
            [
              "site-name",
              "test.buildertrend.net"
            ],
            [
              "transaction-id",
              "4787c7be-f1c0-4deb-afda-919c42fd3ca2"
            ],
            [
              "url",
              "https://test.buildertrend.net/api/OnlinePaymentsOnboarding/CustomerVerificationSnapshot"
            ]
          ],
          "title": "System.InvalidOperationException: Nullable object must have a value.",
          "timestamp": 1693270023.193431,
          "_ref": 5790930,
          "event_id": "1086cec6bd3248ea82b18a8e4b7a3337",
          "dist": null,
          "hashes": [
            "eb3c4ce7af366d294939ff7e23274334",
            "3a3fdf5c308f6799f395c8be6f403e41"
          ],
          "level": "error",
          "received": 1693270023.242564,
          "culprit": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs in CustomerOnboardingServiceSnapshotIndividual OnlinePaymentsOnboardingManager.GetSnapshotIndividualFromRequest(Upda...",
          "metadata": {
            "function": "CustomerOnboardingServiceSnapshotIndividual OnlinePaymentsOnboardingManager.GetSnapshotIndividualFromRequest(UpdateCustomOnboardingRequestIndividual individual)",
            "filename": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
            "type": "System.InvalidOperationException",
            "in_app_frame_mix": "mixed",
            "value": "Nullable object must have a value.",
            "display_title_with_tree_label": false
          },
          "fingerprint": [
            "{{ default }}"
          ],
          "_metrics": {
            "bytes.stored.event": 47425,
            "bytes.ingested.event": 26644
          },
          "user": {
            "username": "Tommy Hyre",
            "data": {
              "other": {
                "Global User Id": "Tommy Hyre (686792) - ",
                "Jobsite ID": "-1",
                "BTAdminLink": "https://test.buildertrend.net/btadmin/adminBuilders.aspx?builderid=98068",
                "Builder": "Hyre Builders Build Buildings (98068)",
                "Portal Login Type": "Internal Users"
              }
            },
            "id": "686792"
          },
          "type": "error",
          "issue_id": "4432298658",
          "contexts": {
            "Current Culture": {
              "name": "en-US",
              "type": "Current Culture",
              "calendar": "GregorianCalendar",
              "display_name": "English (United States)"
            },
            "os": {
              "name": "Windows",
              "raw_description": "Microsoft Windows 10.0.17763 ",
              "version": "10",
              "build": "17763",
              "type": "os"
            },
            "app": {
              "type": "app",
              "app_start_time": "2023-08-28T22:13:26.068863+00:00"
            },
            "client_os": {
              "name": "Windows",
              "type": "os"
            },
            "ThreadPool Info": {
              "available_worker_threads": 32764,
              "available_completion_port_threads": 1000,
              "max_completion_port_threads": 1000,
              "min_worker_threads": 4,
              "max_worker_threads": 32767,
              "min_completion_port_threads": 4,
              "type": "ThreadPool Info"
            },
            "device": {
              "boot_time": "2023-08-26T08:51:25.3519173+00:00",
              "timezone_display_name": "(UTC-06:00) Central Time (US & Canada)",
              "type": "device",
              "timezone": "Central Standard Time"
            },
            "Tracing Values": {
              "TraceId": "e23a7d4457305bc4",
              "DataDogSpanId": "8771523465792399684",
              "type": "Tracing Values",
              "DataDogTraceId": "3566393972835971242"
            },
            "runtime": {
              "name": ".NET Framework",
              "raw_description": ".NET Framework 4.8.4645.0",
              "type": "runtime",
              "version": "4.8.4645.0"
            },
            "Additional Exception Info": {
              "type": "Additional Exception Info",
              "Source": "mscorlib",
              "InnerExceptionNotes": null
            },
            ".NET Framework": {
              ".NET Framework Client": "\"v4.8\", \"v4.0.0.0\"",
              ".NET Framework Full": "\"v4.8\"",
              ".NET Framework ": "\"v2.0.50727\", \"v3.0\", \"v3.5\"",
              "type": ".NET Framework"
            },
            "Request Items": {
              "IsWebAPI": true,
              "type": "Request Items",
              "ConnectionStackCount": 0
            },
            "Mobile App": {
              "type": "Mobile App",
              "MobileAppType": "",
              "NativeAppVersion": null
            },
            "Custom Message": {
              "CustomMessage": "",
              "type": "Custom Message"
            },
            "browser": {
              "name": "Google Chrome",
              "version": "116",
              "type": "browser"
            },
            "Form Post Values": {
              "type": "Form Post Values",
              "FormPostValues": ""
            }
          },
          "_ref_version": 2,
          "project": 5790930,
          "location": "C:\\adoBuild1\\_work\\4\\s\\BusinessLogic.Managers\\OnlinePaymentsOnboardingManager.cs",
          "message": "",
          "request": {
            "query_string": [],
            "api_target": null,
            "fragment": null,
            "data": null,
            "inferred_content_type": "application/json",
            "cookies": null,
            "url": "https://test.buildertrend.net/api/OnlinePaymentsOnboarding/CustomerVerificationSnapshot",
            "method": "PUT",
            "headers": [
              [
                "Accept",
                "*/*"
              ],
              [
                "Accept-Encoding",
                "gzip, deflate, br"
              ],
              [
                "Accept-Language",
                "en-US,en;q=0.9"
              ],
              [
                "Baggage",
                "sentry-environment=test.buildertrend.net,sentry-release=313498-test,sentry-public_key=90ea83bd365f425fad8c55d22a905a58,sentry-trace_id=ce3cdc15377e4717a3019adb6c74addf,sentry-sample_rate=0.0001"
              ],
              [
                "Content-Length",
                "840"
              ],
              [
                "Content-Type",
                "application/json"
              ],
              [
                "Host",
                "test.buildertrend.net"
              ],
              [
                "Origin",
                "https://test.buildertrend.net"
              ],
              [
                "Portaltype",
                "1"
              ],
              [
                "Referer",
                "https://test.buildertrend.net/app/OnlinePaymentSettings"
              ],
              [
                "Sec-Ch-Ua",
                "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\""
              ],
              [
                "Sec-Ch-Ua-Mobile",
                "?0"
              ],
              [
                "Sec-Ch-Ua-Platform",
                "\"Windows\""
              ],
              [
                "Sec-Fetch-Dest",
                "empty"
              ],
              [
                "Sec-Fetch-Mode",
                "cors"
              ],
              [
                "Sec-Fetch-Site",
                "same-origin"
              ],
              [
                "Sentry-Trace",
                "ce3cdc15377e4717a3019adb6c74addf-84bd4129f3fc2a41-0"
              ],
              [
                "User-Agent",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
              ],
              [
                "Via",
                "1.1 google"
              ],
              [
                "X-Client-Geo-City",
                "Omaha"
              ],
              [
                "X-Client-Geo-Latlong",
                "41.256537,-95.934503"
              ],
              [
                "X-Client-Geo-Region",
                "US"
              ],
              [
                "X-Client-Geo-Subregion",
                "USNE"
              ],
              [
                "X-Client-Ip",
                "35.184.88.245"
              ],
              [
                "X-Cloud-Trace-Context",
                "9b49dcbf3fa0c9d48ff6ba0f035a38c9/15115626368681648955"
              ],
              [
                "X-Datadog-Origin",
                "rum"
              ],
              [
                "X-Datadog-Parent-Id",
                "3436436342372330034"
              ],
              [
                "X-Datadog-Sampling-Priority",
                "1"
              ],
              [
                "X-Datadog-Trace-Id",
                "3566393972835971242"
              ],
              [
                "X-Forwarded-For",
                "35.184.88.245,34.96.120.197"
              ],
              [
                "X-Forwarded-Proto",
                "https"
              ]
            ],
            "env": null
          },
          "web_url": "https://sentry.io/organizations/buildertrend/issues/4432298658/events/1086cec6bd3248ea82b18a8e4b7a3337/",
          "release": "313498-test",
          "grouping_config": {
            "enhancements": "eJybzDRxc15qeXFJZU6qlZGBkbGugaGuoeEEAHJMCAM",
            "id": "newstyle:2023-01-11"
          },
          "modules": {
            "Hangfire.Heartbeat": "1.0.0.0",
            "Microsoft.IO.RecyclableMemoryStream": "1.2.2.0",
            "System.Net.Http.Primitives": "4.2.29.0",
            "Serilog.Extensions.Logging": "2.0.0.0",
            "Google.Api.Gax.Grpc.GrpcCore": "3.5.0.0",
            "System.IdentityModel": "4.0.0.0",
            "App_Web_rootmaster.master.7371103c": "0.0.0.0",
            "Microsoft.AspNetCore.Http.Connections.Client": "3.0.0.0",
            "System.Security.Principal.Windows": "5.0.0.0",
            "System.Workflow.Activities": "4.0.0.0",
            "Nager.Country": "3.1.1.0",
            "Microsoft.Extensions.Configuration.CommandLine": "3.1.0.0",
            "TimeZoneConverter": "3.3.0.0",
            "XmpCore": "6.1.10.1",
            "Xero.NetStandard.OAuth2Client": "1.6.0.0",
            "System.Buffers": "4.0.3.0",
            "Microsoft.Extensions.Options.ConfigurationExtensions": "3.1.0.0",
            "mscorlib": "4.0.0.0",
            "Microsoft.AspNetCore.Hosting.Abstractions": "2.2.0.0",
            "Google.Apis.Auth": "1.55.0.0",
            "SMDiagnostics": "4.0.0.0",
            "aspNetMime": "2.8.0.0",
            "Serilog.Sinks.Debug": "2.0.0.0",
            "Microsoft.AspNetCore.Http.Abstractions": "2.2.0.0",
            "System.CodeDom": "7.0.0.0",
            "System.Security.Cryptography.Xml": "4.0.1.0",
            "System.Data.SqlClient": "4.6.1.5",
            "Atalasoft.dotImage": "11.4.0.349",
            "Handlebars": "1.9.5.0",
            "Atalasoft.Shared": "11.4.0.349",
            "Intuit.Ipp.EntitlementService": "14.6.3.4",
            "System.ServiceModel.Activation": "4.0.0.0",
            "Microsoft.AspNetCore.SignalR.Common": "3.0.0.0",
            "Serilog.Sinks.File": "2.0.0.0",
            "App_Web_btdropdownmenuitem.ascx.72c91787": "0.0.0.0",
            "Buildertrend_WebLib": "1.0.8640.38648",
            "System": "4.0.0.0",
            "App_Web_rebatelist.aspx.3c6d9385": "0.0.0.0",
            "System.Security.Cryptography.Algorithms": "4.0.0.0",
            "SerilogTraceListener": "0.0.0.0",
            "Microsoft.Owin.Security.Cookies": "4.2.0.0",
            "Clients.Atalasoft": "1.0.0.0",
            "WebGrease": "1.5.2.14234",
            "App_Web_reacttemplatelist.aspx.114a796e": "0.0.0.0",
            "Microsoft.AspNetCore.SignalR.Client.Core": "3.0.0.0",
            "System.Net.Requests": "4.0.0.0",
            "Serilog.Sinks.Console": "3.1.1.0",
            "App_Web_timepicker.ascx.6bb32623": "0.0.0.0",
            "Microsoft.AspNet.SignalR.Client": "2.4.3.0",
            "App_Web_menu.ascx.56baee3b": "0.0.0.0",
            "Microsoft.Extensions.FileProviders.Abstractions": "3.1.0.0",
            "Microsoft.AspNet.Identity.Core": "2.0.0.0",
            "Auth0.Core": "7.20.0.0",
            "Microsoft.Extensions.Logging.Debug": "3.1.0.0",
            "System.ServiceModel": "4.0.0.0",
            "Microsoft.VisualBasic": "10.0.0.0",
            "System.IO": "4.0.0.0",
            "App_Web_btdropdownmenu.ascx.72c91787": "0.0.0.0",
            "Atalasoft.dotImage.Ocr": "11.4.0.349",
            "System.Diagnostics.EventLog": "7.0.0.0",
            "Google.Protobuf": "3.19.3.0",
            "System.Threading.Tasks.Dataflow": "4.6.3.0",
            "App_Web_btdropdownchecklistlegacy.ascx.2f5a3276": "0.0.0.0",
            "System.Activities": "4.0.0.0",
            "Pathoschild.Http.Client": "3.2.0.0",
            "System.Web.RegularExpressions": "4.0.0.0",
            "Microsoft.Owin.Security.OAuth": "4.2.0.0",
            "Microsoft.Extensions.FileProviders.Physical": "3.1.0.0",
            "App_Web_btadminnavigationenabledmaster.master.7ab75745": "0.0.0.0",
            "BusinessLogic.Engines": "1.0.0.0",
            "Intuit.Ipp.OAuth2PlatformClient.Diagnostics": "14.6.3.4",
            "Google.Apis.PlatformServices": "1.55.0.0",
            "Microsoft.Build.Utilities.v4.0": "4.0.0.0",
            "Atalasoft.dotImage.Raw": "11.4.0.349",
            "Microsoft.Extensions.Configuration.UserSecrets": "3.1.0.0",
            "Google.Cloud.DevTools.Common": "2.1.0.0",
            "Microsoft.Extensions.Logging.EventSource": "3.1.0.0",
            "Global.Core": "1.0.0.0",
            "System.IO.Compression.FileSystem": "4.0.0.0",
            "Google.Cloud.PubSub.V1": "2.7.0.0",
            "Intuit.Ipp.Core": "14.6.3.4",
            "K4os.Compression.LZ4.Streams": "1.2.16.0",
            "App_Web_asyncjobpicker.ascx.6bb32623": "0.0.0.0",
            "ICSharpCode.SharpZipLib": "1.4.2.13",
            "App_Web_btdropdownlistlegacy.ascx.2f5a3276": "0.0.0.0",
            "Buildertrend.Utilities.Core": "1.0.5.0",
            "System.ComponentModel.DataAnnotations": "4.0.0.0",
            "App_Web_masterpagebase.master.7371103c": "0.0.0.0",
            "Grpc.Net.Client": "2.0.0.0",
            "System.Web.DynamicData": "4.0.0.0",
            "Google.Api.Gax": "3.6.0.0",
            "Elastic.Apm": "1.16.1.0",
            "App_Web_default.aspx.cdcab7d2": "0.0.0.0",
            "Microsoft.Extensions.DependencyModel": "2.0.4.0",
            "Intuit.Ipp.Security": "14.6.3.4",
            "Microsoft.AspNetCore.Http.Connections.Common": "3.0.0.0",
            "Microsoft.Extensions.Configuration.FileExtensions": "3.1.0.0",
            "App_Web_default.aspx.41cb4f82": "0.0.0.0",
            "Microsoft.AspNet.Identity.Owin": "2.0.0.0",
            "Intuit.Ipp.Utility": "14.6.3.4",
            "RedLockNet.SERedis": "2.2.0.0",
            "App_Web_googlemap.ascx.c03d9170": "0.0.0.0",
            "OSExtensions": "1.0.0.0",
            "antlr.runtime": "2.7.6.2",
            "Handlers.Merchants": "1.0.0.0",
            "AngleSharp": "0.9.9.0",
            "App_Web_default.aspx.ae7ca9bd": "0.0.0.0",
            "BusinessLogic.Managers": "1.0.0.0",
            "Serilog.Enrichers.Thread": "2.0.0.0",
            "Microsoft.Extensions.Configuration.Abstractions": "3.1.0.0",
            "System.Net.Http.WebRequest": "4.0.0.0",
            "App_Browsers": "0.0.0.0",
            "System.Diagnostics.DiagnosticSource": "5.0.0.0",
            "App_Web_btcheckbox.ascx.2f5a3276": "0.0.0.0",
            "Grpc.Core.Api": "2.0.0.0",
            "BT_Encryptor": "1.0.0.0",
            "IppDotNetSdkForQuickBooksApiV3": "14.6.3.4",
            "Handlers.IntegrationHandlers": "1.0.8640.38637",
            "Microsoft.Extensions.Logging.Console": "3.1.0.0",
            "App_Web_summarygrid.aspx.cdcab7d2": "0.0.0.0",
            "RebateService.Shared.Contracts": "1.0.42.0",
            "App_Web_btdatetimebox.ascx.6bb32623": "0.0.0.0",
            "System.ServiceModel.Web": "4.0.0.0",
            "App_Web_adminautologin.aspx.41cb4f82": "0.0.0.0",
            "MongoDB.Libmongocrypt": "1.7.0.0",
            "HtmlAgilityPack": "1.11.24.0",
            "App_Web_btadminnavigationdisabledmaster.master.7ab75745": "0.0.0.0",
            "AdvancedIntellect.Ssl": "2.0.0.6",
            "Intuit.Ipp.QueryFilter": "14.6.3.4",
            "System.Configuration": "4.0.0.0",
            "SimpleObfuscator": "1.0.0.0",
            "Microsoft.AspNetCore.Hosting.Server.Abstractions": "2.2.0.0",
            "System.Security": "4.0.0.0",
            "System.Web.Services": "4.0.0.0",
            "DAL": "1.0.0.0",
            "ZstdSharp": "0.6.2.0",
            "App_Web_btentitymapping.ascx.6bb32623": "0.0.0.0",
            "System.Web.Http.WebHost": "5.2.7.0",
            "Magick.NET-Q16-AnyCPU": "13.1.0.0",
            "AWSSDK.Core": "3.3.0.0",
            "System.Numerics.Vectors": "4.1.4.0",
            "Clients.WebApiLib": "1.0.0.0",
            "System.Threading.Channels": "5.0.0.0",
            "GenericParsing": "1.1.3.17129",
            "Datadog.Trace.ClrProfiler.Managed.Loader": "2.14.0.0",
            "SharpCompress": "0.30.1.0",
            "Antlr3.Runtime": "3.4.1.9004",
            "App_Web_tooltip.ascx.6bb32623": "0.0.0.0",
            "Auth0.ManagementApi": "7.20.0.0",
            "System.Xml.Linq": "4.0.0.0",
            "System.Diagnostics.PerformanceCounter": "5.0.0.0",
            "Microsoft.AspNetCore.Http.Features": "3.1.0.0",
            "Xero.NetStandard.OAuth2": "0.0.0.0",
            "System.Runtime.DurableInstancing": "4.0.0.0",
            "System.IdentityModel.Tokens.Jwt": "6.10.2.0",
            "Google.Api.Gax.Grpc": "3.5.0.0",
            "Microsoft.Extensions.Logging.Abstractions": "3.1.0.0",
            "System.Windows.Forms": "4.0.0.0",
            "Google.Apis": "1.55.0.0",
            "Polly": "7.0.0.0",
            "Nest": "7.0.0.0",
            "Avalara.AvaTax.RestClient.net45": "20.9.0.0",
            "K4os.Compression.LZ4": "1.2.16.0",
            "System.Threading.Tasks": "4.0.0.0",
            "RedLockNet.Abstractions": "2.2.0.0",
            "Microsoft.Web.RedisSessionStateProvider": "4.0.1.0",
            "System.Security.AccessControl": "6.0.0.0",
            "Imazen.Common": "0.7.8.0",
            "Microsoft.Bcl.AsyncInterfaces": "6.0.0.0",
            "PuppeteerSharp": "10.1.2.0",
            "IP2Location": "4.0.0.0",
            "Ude.NetStandard": "1.0.2.0",
            "System.Device": "4.0.0.0",
            "MongoDB.Driver": "2.19.1.0",
            "System.Security.Permissions": "7.0.0.0",
            "QbSync.QbXml": "0.0.3.0",
            "Buildertrend.Utilities.Ocr.Veryfi": "1.0.0.0",
            "Microsoft.AspNetCore.Cryptography.KeyDerivation": "7.0.0.0",
            "Microsoft.Extensions.WebEncoders": "2.2.0.0",
            "Hangfire.Core": "1.7.33.0",
            "Snappier": "1.0.0.0",
            "App_Web_btdatebox.ascx.2f5a3276": "0.0.0.0",
            "App_Web_btdropdownlist.ascx.2f5a3276": "0.0.0.0",
            "System.Data.DataSetExtensions": "4.0.0.0",
            "Microsoft.Extensions.Configuration": "3.1.0.0",
            "Atalasoft.dotImage.WebControls": "11.4.0.349",
            "App_Web_bttextbox.ascx.2f5a3276": "0.0.0.0",
            "System.Data.SqlXml": "4.0.0.0",
            "aspNetIMAP": "1.8.0.0",
            "Intuit.Ipp.Data": "14.6.3.4",
            "Microsoft.Extensions.DependencyInjection.Abstractions": "3.1.22.0",
            "System.Collections.Immutable": "7.0.0.0",
            "Microsoft.CodeDom.Providers.DotNetCompilerPlatform": "2.0.1.0",
            "System.Xaml": "4.0.0.0",
            "Microsoft.Diagnostics.FastSerialization": "1.0.0.0",
            "System.Text.Encoding": "4.0.0.0",
            "Atalasoft.PdfDoc": "11.4.0.349",
            "Hangfire.Pro.Redis": "2.8.20.0",
            "App_Web_bttab.ascx.6bb32623": "0.0.0.0",
            "System.Workflow.ComponentModel": "4.0.0.0",
            "jose-jwt": "4.1.0.0",
            "System.Web.Optimization": "1.1.0.0",
            "VimeoDotNet": "2.0.0.23",
            "Google.Cloud.Iam.V1": "2.3.0.0",
            "System.Net.Http.Extensions": "2.2.29.0",
            "System.Dynamic": "4.0.0.0",
            "DotNetOpenAuth": "3.4.7.11121",
            "Microsoft.Extensions.Configuration.Xml": "2.2.0.0",
            "Buildertrend.Utilities.Ocr": "1.0.0.0",
            "System.Web.Http": "5.2.7.0",
            "System.Net.Http.Json": "5.0.0.0",
            "Dropbox.Api": "6.14.0.0",
            "Microsoft.Diagnostics.Tracing.TraceEvent": "2.0.2.0",
            "System.Xml": "4.0.0.0",
            "Microsoft.Owin.Security.Jwt": "4.2.0.0",
            "System.Runtime.Caching": "4.0.0.0",
            "System.Net.Primitives": "4.0.0.0",
            "Serilog": "2.0.0.0",
            "IdentityModel": "5.1.0.0",
            "Microsoft.Build.Framework": "4.0.0.0",
            "Clients.Hangfire.RecurringJobs": "1.0.0.0",
            "Microsoft.JScript": "10.0.0.0",
            "Atalasoft.dotImage.PdfDoc.Bridge": "11.4.0.349",
            "Microsoft.Extensions.Configuration.Binder": "3.1.0.0",
            "Microsoft.Extensions.DependencyInjection": "3.1.22.0",
            "System.Reflection.Metadata": "5.0.0.0",
            "Microsoft.VisualBasic.Activities.Compiler": "10.0.0.0",
            "System.Runtime.Extensions": "4.0.0.0",
            "Pipelines.Sockets.Unofficial": "1.0.0.0",
            "Atalasoft.dotImage.Lib": "11.4.0.349",
            "Swashbuckle.Core": "1.0.0.0",
            "Serilog.Enrichers.Environment": "2.0.0.0",
            "Microsoft.AspNet.SessionState.SessionStateModule": "1.1.0.0",
            "App_Web_adminmain.aspx.41cb4f82": "0.0.0.0",
            "Clients.WebApi": "1.0.0.0",
            "Microsoft.AspNetCore.SignalR.Protocols.Json": "3.0.0.0",
            "MetadataExtractor": "2.7.2.0",
            "Google.Apis.Storage.v1": "1.55.0.2526",
            "Microsoft.Extensions.Hosting": "3.1.0.0",
            "Excel": "2.1.2.3",
            "Microsoft.Web.Infrastructure": "1.0.0.0",
            "Handlers.Accounting": "1.0.0.0",
            "Intuit.Ipp.DataService": "14.6.3.4",
            "Google.Cloud.Logging.Log4Net": "3.3.0.0",
            "HttpMultipartParser": "2.2.4.0",
            "Google.Api.CommonProtos": "2.5.0.0",
            "Intuit.Ipp.WebHooksService": "14.6.3.4",
            "Intuit.Ipp.Retry": "14.6.3.4",
            "System.IO.Compression": "4.0.0.0",
            "gma.Drawing.ImageInfo": "1.0.0.0",
            "System.Net.Http.Formatting": "5.2.7.0",
            "System.Core": "4.0.0.0",
            "Google.Cloud.Logging.Type": "3.3.0.0",
            "BuilderTrend_Web": "1.0.8640.38803",
            "System.Memory": "4.0.1.2",
            "RestSharp.Serializers.NewtonsoftJson": "106.11.7.0",
            "nClam": "4.0.1.0",
            "App_Web_loginnotrequiredmaster.master.1880769f": "0.0.0.0",
            "Google.Cloud.Logging.V2": "3.4.0.0",
            "System.Runtime.CompilerServices.Unsafe": "6.0.0.0",
            "System.Web.Mobile": "4.0.0.0",
            "System.ServiceModel.Internals": "4.0.0.0",
            "Microsoft.Win32.Registry": "5.0.0.0",
            "System.Web.ApplicationServices": "4.0.0.0",
            "Newtonsoft.Json": "13.0.0.0",
            "System.Interactive.Async": "5.1.0.0",
            "Microsoft.Extensions.Options": "3.1.7.0",
            "DnsClient": "1.6.1.0",
            "NPOI.OpenXml4Net": "2.5.1.0",
            "BTSerializeJSAttribute": "1.2.0.0",
            "WebClientShared": "1.0.0.0",
            "CsvHelper": "15.0.0.0",
            "System.Transactions": "4.0.0.0",
            "Twilio": "5.65.2.0",
            "Microsoft.Owin": "4.2.0.0",
            "Serilog.Settings.Configuration": "3.1.0.0",
            "Google.Api.Gax.Rest": "3.6.0.0",
            "System.Text.Json": "5.0.0.2",
            "Sentry.AspNet": "3.25.0.0",
            "System.Threading.Tasks.Extensions": "4.2.0.1",
            "Google.Apis.Core": "1.55.0.0",
            "Google.Apis.Auth.PlatformServices": "1.55.0.0",
            "System.Data.Linq": "4.0.0.0",
            "Microsoft.Extensions.Primitives": "3.1.7.0",
            "Intuit.Ipp.OAuth2PlatformClient": "14.6.3.4",
            "App_Web_btimagebutton.ascx.2f5a3276": "0.0.0.0",
            "FirebaseAdmin": "1.9.1.0",
            "Datadog.Trace": "2.14.0.0",
            "Atalasoft.dotImage.PdfReader": "11.4.0.349",
            "Atalasoft.dotImage.Pdf": "11.4.0.349",
            "System.Security.Cryptography.Primitives": "4.0.0.0",
            "Microsoft.VisualStudio.TestPlatform.TestFramework": "14.0.0.0",
            "Salesforce.Common": "1.0.0.0",
            "BouncyCastle.Crypto": "1.8.6.0",
            "Microsoft.Extensions.Logging.Configuration": "3.1.0.0",
            "Trirand.Web": "4.5.4.0",
            "AutoMapper": "10.0.0.0",
            "NPOI.OpenXmlFormats": "2.5.1.0",
            "System.Text.Encodings.Web": "6.0.0.0",
            "System.Web.Cors": "5.2.7.0",
            "DAL.Core": "1.0.0.0",
            "Microsoft.Owin.Security.OpenIdConnect": "4.2.0.0",
            "Sentry": "3.25.0.0",
            "System.IO.Pipelines": "7.0.0.0",
            "MongoDB.Bson": "2.19.1.0",
            "Microsoft.AspNetCore.Connections.Abstractions": "3.0.0.0",
            "RestSharp": "106.12.0.0",
            "DotNetZip": "1.16.0.0",
            "Serilog.Sinks.Trace": "2.0.0.0",
            "Hangfire.Dashboard.Management.v2": "0.0.0.0",
            "Microsoft.IdentityModel.Protocols.OpenIdConnect": "5.3.0.0",
            "StrongGrid": "0.50.2.0",
            "Microsoft.Azure.WebJobs": "3.0.18.0",
            "App_Web_adminbuilders.aspx.41cb4f82": "0.0.0.0",
            "Hangfire.Console": "1.4.2.0",
            "MongoDB.Driver.Core": "2.19.1.0",
            "NPOI": "2.5.1.0",
            "System.ServiceModel.Activities": "4.0.0.0",
            "System.Drawing": "4.0.0.0",
            "Global.SignalrModels": "1.0.0.0",
            "KellermanSoftware.Compare-NET-Objects": "4.57.0.0",
            "System.Runtime": "4.0.0.0",
            "System.Runtime.InteropServices.RuntimeInformation": "4.0.0.0",
            "System.Web": "4.0.0.0",
            "System.ComponentModel.Annotations": "4.2.1.0",
            "Handlers.DataAccessHandlers": "1.0.0.0",
            "System.Collections": "4.0.0.0",
            "Elasticsearch.Net": "7.0.0.0",
            "StackExchange.Redis": "2.0.0.0",
            "Microsoft.Extensions.Configuration.Json": "3.1.0.0",
            "LightInject.WebApi": "2.0.0.0",
            "log4net": "2.0.15.0",
            "App_Web_externalnonembeddablemaster.master.af2f93c0": "0.0.0.0",
            "App_Web_bttabcontrol.ascx.6bb32623": "0.0.0.0",
            "Microsoft.AspNetCore.WebUtilities": "2.2.0.0",
            "System.Xaml.Hosting": "4.0.0.0",
            "HtmlSanitizer": "4.0.0.0",
            "Hangfire.AspNet": "0.2.0.0",
            "Atalasoft.dotImage.AdvancedDocClean": "11.4.0.349",
            "netstandard": "2.0.0.0",
            "Google.Cloud.Kms.V1": "2.7.0.0",
            "Grpc.Auth": "2.0.0.0",
            "System.Numerics": "4.0.0.0",
            "Intuit.Ipp.Diagnostics": "14.6.3.4",
            "Microsoft.IdentityModel.Tokens": "6.10.2.0",
            "System.Design": "4.0.0.0",
            "Microsoft.Owin.Host.SystemWeb": "4.2.0.0",
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "3.1.0.0",
            "System.Text.Encoding.Extensions": "4.0.0.0",
            "AWSSDK.SecurityToken": "3.3.0.0",
            "Microsoft.Extensions.Http": "2.2.0.0",
            "Microsoft.Azure.WebJobs.Host": "3.0.18.0",
            "Microsoft.Extensions.Logging.EventLog": "3.1.0.0",
            "System.EnterpriseServices": "4.0.0.0",
            "Microsoft.IdentityModel.Logging": "6.10.2.0",
            "System.Drawing.Common": "7.0.0.0",
            "Microsoft.Extensions.Logging": "3.1.0.0",
            "Microsoft.AspNetCore.Http": "2.2.2.0",
            "Global.DependencyResolver": "1.0.0.0",
            "Microsoft.AspNetCore.Http.Extensions": "2.2.0.0",
            "App_Web_btaddress.ascx.6bb32623": "0.0.0.0",
            "App_Web_masterpagebuilder.master.7371103c": "0.0.0.0",
            "Microsoft.Extensions.FileSystemGlobbing": "3.1.0.0",
            "App_Web_btadminmaster.master.91644b2f": "0.0.0.0",
            "Braintree": "5.15.0.0",
            "Microsoft.AspNetCore.SignalR.Client": "3.0.0.0",
            "Intuit.Ipp.GlobalTaxService": "14.6.3.4",
            "Clients.Hangfire.Common": "1.0.0.0",
            "System.Runtime.Serialization": "4.0.0.0",
            "System.Web.Http.Cors": "5.2.7.0",
            "BuilderTrend": "0.0.0.0",
            "Microsoft.Extensions.Hosting.Abstractions": "3.1.0.0",
            "Microsoft.Extensions.Logging.Log4Net.AspNetCore": "2.2.12.0",
            "Magick.NET.Core": "13.1.0.0",
            "System.Net.Http": "4.0.0.0",
            "Salesforce.Force": "1.0.0.0",
            "K4os.Hash.xxHash": "1.0.6.0",
            "System.Resources.ResourceManager": "4.0.0.0",
            "Global.Utilities": "1.0.0.0",
            "Microsoft.IdentityModel.JsonWebTokens": "6.10.2.0",
            "Microsoft.DotNet.PlatformAbstractions": "2.0.4.0",
            "Microsoft.Azure.Functions.Extensions": "1.1.0.0",
            "Grpc.Core": "2.0.0.0",
            "System.Text.Encoding.CodePages": "7.0.0.0",
            "Intuit.Ipp.Exception": "14.6.3.4",
            "NodaTime": "3.1.9.0",
            "Clients.Hangfire.OneTimeJobs": "1.0.0.0",
            "Microsoft.Owin.Security": "4.2.0.0",
            "Persits.Email": "5.4.0.4478",
            "Microsoft.AspNetCore.Cryptography.Internal": "7.0.0.0",
            "Elastic.Apm.AspNetFullFramework": "1.16.1.0",
            "LumenWorks.Framework.IO": "3.8.0.0",
            "Google.Cloud.Storage.V1": "3.6.0.0",
            "System.Runtime.InteropServices": "4.0.0.0",
            "System.WorkflowServices": "4.0.0.0",
            "Microsoft.Net.Http.Headers": "2.2.8.0",
            "MimeTypesMap": "1.0.8.0",
            "UnitsNet": "4.0.0.0",
            "JsonSubTypes": "1.5.2.0",
            "Microsoft.Extensions.ObjectPool": "2.2.0.0",
            "MoreLinq": "3.3.2.0",
            "ChargeBee": "3.8.0.0",
            "Owin": "1.0.0.0",
            "System.Linq": "4.0.0.0",
            "Intuit.Ipp.ReportService": "14.6.3.4",
            "Imageflow.Net": "0.0.0.0",
            "LightInject": "6.5.2.0",
            "System.Linq.Async": "5.1.0.0",
            "JWT": "4.0.0.0",
            "System.Threading": "4.0.0.0",
            "System.Configuration.ConfigurationManager": "4.0.2.0",
            "App_Web_btlistpager.ascx.6bb32623": "0.0.0.0",
            "CaptchaImage": "1.0.2770.19138",
            "Sentry.DiagnosticSource": "3.25.0.0",
            "Grpc.Net.Common": "2.0.0.0",
            "Ical.Net": "1.0.0.0",
            "Microsoft.IdentityModel.Protocols": "5.3.0.0",
            "System.Workflow.Runtime": "4.0.0.0",
            "App_Web_applicationdefaults.aspx.41cb4f82": "0.0.0.0",
            "App_global.asax": "0.0.0.0",
            "Microsoft.AspNetCore.StaticFiles": "2.2.0.0",
            "Microsoft.CSharp": "4.0.0.0",
            "NPOI.OOXML": "2.5.1.0",
            "System.ValueTuple": "4.0.3.0",
            "Global.DependencyInjection": "1.0.0.0",
            "System.Data": "4.0.0.0",
            "System.Web.Extensions": "4.0.0.0"
          },
          "ingest_path": [
            {
              "public_key": "XE7QiyuNlja9PZ7I9qJlwQotzecWrUIN91BAO7Q5R38",
              "version": "23.8.0"
            }
          ],
          "key_id": "1682840",
          "platform": "csharp",
          "url": "https://sentry.io/api/0/projects/buildertrend/btnet-dotnet/events/1086cec6bd3248ea82b18a8e4b7a3337/",
          "nodestore_insert": 1693270024.48233,
          "sdk": {
            "version": "3.25.0",
            "integrations": null,
            "name": "sentry.dotnet",
            "packages": [
              {
                "name": "nuget:Sentry.AspNet",
                "version": "3.25.0"
              },
              {
                "name": "nuget:sentry.dotnet",
                "version": "3.25.0"
              }
            ]
          }
        }
      },
      "actor": {
        "id": "sentry",
        "type": "application",
        "name": "Sentry"
      }
    },
    "resource": {
      "type": "cloud_run_revision",
      "labels": {
        "project_id": "clear-network-397314",
        "revision_name": "sentry-test3-00017-heb",
        "location": "us-central1",
        "service_name": "sentry-test3",
        "configuration_name": "sentry-test3"
      }
    },
    "timestamp": "2023-08-29T00:47:16.259881Z",
    "labels": {
      "goog-managed-by": "cloudfunctions",
      "instanceId": "00e67600735173991238923aef017db16f72628943789f368ebd543b8dc3160ce17800a4c6152b8ec3cc3539a8e38823680bd607304b8d4249399d21059ba0b19ebd"
    },
    "logName": "projects/clear-network-397314/logs/run.googleapis.com%2Fstdout",
    "receiveTimestamp": "2023-08-29T00:47:16.598695906Z"
  };